### ISSUE TITLE
交互式应用，jupyter报错端口错误

### ISSUE THREAD

**Issue by g-zhangpp** [PKUHPC/SCOW#1002]
新建一个juputer任务，输出文件中报错端口问题

![微信图片_20231124135019](https://github.com/PKUHPC/SCOW/assets/46897488/a2df6479-31e4-46db-a255-8f9f22226f08)

**Comment by huangjun0210** [comment]
把第一行报错解决

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
