### ISSUE TITLE
[Help] 创建初始化管理员用户失败

### ISSUE THREAD

**Issue by xxxxyflixxxx** [PKUHPC/SCOW#1022]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

在系统初始化界面，创建初始管理员用户报错：“服务器出错了，添加用户失败”；查看auth日志无报错，查看mis-server日志报错："msg":"HTTP Error when calling auth HTTP API. Status code 501"

### 运行环境 | Environment

```Markdown
- OS:CentOS7.9
- Scheduler:slurm
- Docker:24.0.7
- Docker-compose:v2.21.0
- SCOW cli:1.2.1
- SCOW:mater
- Adapter:1.3.0
```

**Comment by huangjun0210** [comment]
请上传更多的日志信息、报错信息

**Comment by xxxxyflixxxx** [comment]
docker logs mis-server
{"level":30,"time":"2023-12-05T03:00:48.522Z","pid":18,"hostname":"4a4f96c38ce4","req":"as","path":"/scow.server.InitService/QuerySystemInitialized","msg":"Starting request"}
{"level":30,"time":"2023-12-05T03:00:48.524Z","pid":18,"hostname":"4a4f96c38ce4","req":"as","path":"/scow.server.InitService/QuerySystemInitialized","msg":"Request completed."}
{"level":30,"time":"2023-12-05T03:00:48.528Z","pid":18,"hostname":"4a4f96c38ce4","req":"at","path":"/scow.server.InitService/CreateInitAdmin","msg":"Starting request"}
{"level":50,"time":"2023-12-05T03:00:48.547Z","pid":18,"hostname":"4a4f96c38ce4","msg":"HTTP Error when calling auth HTTP API. Status code 501"}
{"level":50,"time":"2023-12-05T03:00:48.555Z","pid":18,"hostname":"4a4f96c38ce4","msg":"Error creating user in auth."}
{"level":50,"time":"2023-12-05T03:00:48.555Z","pid":18,"hostname":"4a4f96c38ce4","req":"at","path":"/scow.server.InitService/CreateInitAdmin","code":13,"message":"Error creating user 18 in auth.","msg":"Error occurred. Return the error."}

**Comment by xxxxyflixxxx** [comment]
还需要看其他服务日志吗

**Comment by xxxxyflixxxx** [comment]
auth日志如下，并未见明显报错
{"level":30,"time":"2023-12-07T02:43:54.180Z","pid":18,"hostname":"8c042305b2fc","reqId":"req-1o","req":{"method":"GET","url":"/capabilities","hostname":"auth:5000","remoteAddress":"172.19.0.5","remotePort":38198},"msg":"incoming request"}
{"level":30,"time":"2023-12-07T02:43:54.180Z","pid":18,"hostname":"8c042305b2fc","reqId":"req-1o","res":{"statusCode":200},"responseTime":0.7274429798126221,"msg":"request completed"}
{"level":30,"time":"2023-12-07T02:43:54.191Z","pid":18,"hostname":"8c042305b2fc","reqId":"req-1p","req":{"method":"GET","url":"/user?identityId=admin","hostname":"auth:5000","remoteAddress":"172.19.0.5","remotePort":38198},"msg":"incoming request"}
{"level":30,"time":"2023-12-07T02:43:54.286Z","pid":18,"hostname":"8c042305b2fc","reqId":"req-1p","msg":"Command execCommand getent passwd admin, options %o"}
{"level":30,"time":"2023-12-07T02:43:54.286Z","pid":18,"hostname":"8c042305b2fc","reqId":"req-1p","res":{"statusCode":200},"responseTime":95.55927801132202,"msg":"request completed"}
{"level":30,"time":"2023-12-07T02:43:56.151Z","pid":18,"hostname":"8c042305b2fc","reqId":"req-1q","req":{"method":"POST","url":"/user","hostname":"auth:5000","remoteAddress":"172.19.0.5","remotePort":38198},"msg":"incoming request"}
{"level":30,"time":"2023-12-07T02:43:56.152Z","pid":18,"hostname":"8c042305b2fc","reqId":"req-1q","res":{"statusCode":501},"responseTime":0.8603149950504303,"msg":"request completed"}

**Comment by huangjun0210** [comment]
ssh认证不支持创建用户

**Comment by xxxxyflixxxx** [comment]
os上和slurm都已经有这个用户了，界面提示：可以创建认证系统已存在的用。

**Comment by vanstriker** [comment]
不建议使用ssh认证，后续版本可能会取消该认证方式
