### ISSUE TITLE
[Bug] 交互式应用从界面上无法链接

### ISSUE THREAD

**Issue by liyi8611** [PKUHPC/SCOW#1023]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

通过scow我创建了一个VSCode的交互式应用，在portal上无法链接应用。

### 期望结果 | What did you expect to happen

期望通过scow portal可以连接应用。

### 复现方法 | Steps To Reproduce

1. scow使用官方是master版本容器搭建：
[root@localhost ~]# docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
mirrors.pku.edu.cn/pkuhpc-icode/scow   master              eb294e51b597        7 days ago          845 MB
redis                                  alpine              246a9110fd9e        3 weeks ago         43.4 MB
mysql                                  8                   a3b6608898d6        5 weeks ago         596 MB
ghcr.io/pkuhpc/novnc-client-docker     master              3aa392d6e990        11 months ago       40.2 MB

2. scow-slurm adpter版本是v1.0.0，通过docker查看scow-portal-server日志提示以下错误：
{"level":30,"time":"2023-12-04T10:05:39.819Z","pid":19,"hostname":"4f33de71f98c","req":"6h","path":"/scow.portal.AppService/ListAppSessions","msg":"Request completed."}
{"level":30,"time":"2023-12-04T10:05:48.968Z","pid":19,"hostname":"4f33de71f98c","req":"6i","path":"/scow.portal.AppService/ListAppSessions","msg":"Starting request"}
{"level":20,"time":"2023-12-04T10:05:48.968Z","pid":19,"hostname":"4f33de71f98c","msg":"Read dir config apps of id app1 from /etc/scow/apps/app1.yaml"}
{"level":20,"time":"2023-12-04T10:05:49.022Z","pid":19,"hostname":"4f33de71f98c","msg":"Read dir config apps of id emacs from /etc/scow/apps/emacs.yml"}
{"level":20,"time":"2023-12-04T10:05:49.060Z","pid":19,"hostname":"4f33de71f98c","msg":"Read dir config apps of id vscode from /etc/scow/apps/vscode.yml"}
{"level":30,"time":"2023-12-04T10:05:49.463Z","pid":19,"hostname":"4f33de71f98c","req":"6i","path":"/scow.portal.AppService/ListAppSessions","msg":"Command execCommand eval echo ~root, options %o"}
{"level":20,"time":"2023-12-04T10:05:49.463Z","pid":19,"hostname":"4f33de71f98c","req":"6i","path":"/scow.portal.AppService/ListAppSessions","msg":"Command 'eval echo ~root' completed. stdout /root, stderr "}
{"level":40,"time":"2023-12-04T10:05:49.809Z","pid":19,"hostname":"4f33de71f98c","req":"6i","path":"/scow.portal.AppService/ListAppSessions","msg":"T**he method is not supported with the current scheduler adapter version. To use this method, the scheduler adapter must be upgraded to the version 1.3.0 or higher."**}

3. 以上问题提示要升级到1.3.0的版本，因此使用scow-slurm-adapter master分支重新编译，编译后，scow-portal-server报以下错误：
{"level":20,"time":"2023-12-05T09:57:13.838Z","pid":19,"hostname":"4f33de71f98c","msg":"Read dir config apps of id vscode from /etc/scow/apps/vscode.yml"}
{"level":30,"time":"2023-12-05T09:57:14.238Z","pid":19,"hostname":"4f33de71f98c","req":"7g","path":"/scow.portal.AppService/ListAppSessions","msg":"Command execCommand eval echo ~root, options %o"}
{"level":20,"time":"2023-12-05T09:57:14.238Z","pid":19,"hostname":"4f33de71f98c","req":"7g","path":"/scow.portal.AppService/ListAppSessions","msg":"Command 'eval echo ~root' completed. stdout /root, stderr "}
{"level":40,"time":"2023-12-05T09:57:14.605Z","pid":19,"hostname":"4f33de71f98c","req":"7g","path":"/scow.portal.AppService/ListAppSessions","msg":"**unknown service scow.scheduler_adapter.AppService**"}
{"level":30,"time":"2023-12-05T09:57:14.622Z","pid":19,"hostname":"4f33de71f98c","req":"7g","path":"/scow.portal.AppService/ListAppSessions","msg":"Request completed."}

### 运行环境 | Environment

```Markdown
- OS: CentOS 7.9
- Scheduler: slurm 23.02.6
- Docker: Docker version 1.13.1, build 7d71120/1.13.1
- Docker-compose: Docker Compose version v2.10.1
- SCOW cli: 1.2.2
- SCOW: master
- Adapter: v1.0.0和master
```

**Comment by huangjun0210** [comment]
看看VSCode这个应用的日志

**Comment by huangjun0210** [comment]
交互式应用正常吗？

**Comment by liyi8611** [comment]
> 交互式应用正常吗？

应用是正常的，通过portal可以看到，但是在界面上一直提示“应用还没准备好”
![image](https://github.com/PKUHPC/SCOW/assets/134384710/c3b40cff-a924-4161-90c2-9543376113bc)

进入到引用目录，通过slurm-*.out日志，可以看到vscode的链接，通过server_session_info.json获取到密码后，通过浏览器能直接登录，如下图：
![image](https://github.com/PKUHPC/SCOW/assets/134384710/c5669927-0485-4043-8cfb-1c7735c6ecc5)
![image](https://github.com/PKUHPC/SCOW/assets/134384710/30727d3e-472a-41b2-8ae1-7b927fd60ee3)

**Comment by liyi8611** [comment]
这是连接上的效果：
![image](https://github.com/PKUHPC/SCOW/assets/134384710/5569a089-f818-4215-9bd3-40f59c2d0194)

有一个疑问：slurm-*.out展示的链接是0.0.0.0:47477，而我通过浏览器链接的是slurm的服务器的IP地址，是否跟这个有关系呢？

**Comment by huangjun0210** [comment]
你的计算节点的主机列表写到socw的/etc/hosts了没？

**Comment by liyi8611** [comment]
> 你的计算节点的主机列表写到scow的/etc/hosts了没？

没有加/etc/hosts，应该加什么域名呢？

**Comment by huangjun0210** [comment]
将主机清单加到scow的/etc/hosts就可以了，看你的slurm.conf里面计算节点用的什么主机名，这里就什么名

**Comment by huangjun0210** [comment]
`unknown service scow.scheduler_adapter.AppService` 这个报错，你拉一下最新的适配器代码，编译一下

**Comment by liyi8611** [comment]
> `unknown service scow.scheduler_adapter.AppService` 这个报错，你拉一下最新的适配器代码，编译一下

我就是取最新的master代码编译的slurm-adapter报这个错？你是指重新编译哪个呢？

**Comment by huangjun0210** [comment]
再拉一下适配器的代码编译，https://github.com/PKUHPC/scow-slurm-adapter，刚修复了这个问题

**Comment by liyi8611** [comment]
> 再拉一下适配器的代码编译，`https://github.com/PKUHPC/scow-slurm-adapter，` 刚修复了`unknown service scow.scheduler_adapter.AppService `这个报错

可以了，非常棒

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
