### ISSUE TITLE
现在给获取分区接口增加一个query字段

### ISSUE THREAD

**Issue by kyrieqing7** [PKUHPC/SCOW#1025]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

现在portal-web和portal-server都能正常传值accountName,但grpc调用slurm-adaptor时slurm-adaptor不能正常接收accountName字段，为空
![3821701954779_ pic](https://github.com/PKUHPC/SCOW/assets/148175791/cbba6bc7-cec2-4220-be8f-ffce2f7fc51a)
![3851701954932_ pic](https://github.com/PKUHPC/SCOW/assets/148175791/672f005d-5d7d-4a73-bbee-6de3af8b45de)

### 期望结果 | What did you expect to happen

现在还需要改动那里能讲正常传值到slurm-adaptor

### 之前运行正常吗？ | Did this work before?

无

### 复现方法 | Steps To Reproduce

无

### 运行环境 | Environment

```Markdown
- OS:
- Scheduler:
- Docker:
- Docker-compose:
- SCOW cli:
- SCOW:
- Adapter:
```

### 备注 | Anything else?

无

**Comment by huangjun0210** [comment]
请参照这个文档https://pkuhpc.github.io/SCOW/docs/integration

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
