### ISSUE TITLE
本地部署完成开发环境，怎么看效果

### ISSUE THREAD

**Issue by g-zhangpp** [PKUHPC/SCOW#1029]
老师，我本地部署了开发环境，修改了部分功能，请问在本地怎么通过浏览器查看修改的效果，我访问本地80端口，不能访问scow界面。

**Comment by lingbozeng** [comment]
请使用issue模板详细描述一下问题，看看服务是否正常启动，防火墙有没有放开80端口的访问

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
