### ISSUE TITLE
求教：运行pnpm prepareDev时报错Failure: plugin ts-proto: exec: "node_modules/ts-proto/protoc-gen-ts_proto": file does not exist

### ISSUE THREAD

**Issue by g-zhangpp** [PKUHPC/SCOW#1030]
运行pnpm prepareDev时报错Failure: plugin ts-proto: exec: "node_modules/ts-proto/protoc-gen-ts_proto": file does not exist
![微信图片_20231209082843](https://github.com/PKUHPC/SCOW/assets/46897488/c536b82b-7084-46f7-9786-c43e1704bdf9)

**Comment by lingbozeng** [comment]
这个提示是您的ts-proto插件有问题，看看是否正常安装了，可以卸载重新安装试试

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
