### ISSUE TITLE
SCOW源码构建后怎么运行

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#1053]
看了下从源码构建SCOW的文档，镜像构建完成后，请问怎么启动这些镜像？
```
docker build -f docker/Dockerfile.scow -t scow .
```

**Comment by g-zhangpp** [comment]
你这边执行ocker build -f docker/Dockerfile.scow -t scow .构建镜像过程中，有报错码

**Comment by liu-shaobo** [comment]
构建正常，就是不知道不知道构建后，下一步怎么运行，看https://pkuhpc.github.io/SCOW/docs/deploy/install/build-from-source的文档，有点看不懂。
