### ISSUE TITLE
交互式应用能否指定某些应用分配给某些用户

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#1062]
### 为何需要此功能 | Why is this needed
现在的交互式应用配置后，所有用户都能看到；能否指定某些应用分配给某些用户？
比如两个部门，一个用户使用应用A，一个用户使用应用B，希望彼此只能看到自己的应用；

**Comment by huangjun0210** [comment]
目前不支持这个功能，应用所有的用户都可以看到，会根据用户的权限下只允许拉选择可用的账户和分区
