### ISSUE TITLE
执行docker build -f docker/Dockerfile.scow -t scow过程中报错

### ISSUE THREAD

**Issue by g-zhangpp** [PKUHPC/SCOW#1074]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

执行docker build -f docker/Dockerfile.scow -t scow过程中报错
![11](https://github.com/PKUHPC/SCOW/assets/46897488/3a580e05-fdc7-4910-9f7d-9787da6e68b8)

### 运行环境 | Environment

```Markdown
- OS:
- Scheduler:
- Docker:
- Docker-compose:
- SCOW cli:
- SCOW:
- Adapter:
```

**Comment by liu-shaobo** [comment]
看日志是github访问有问题，直接手动 git clone 会有这个问题吗？

**Comment by g-zhangpp** [comment]
已经解决

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
