### ISSUE TITLE
账户的封锁功能无效

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#1080]
### 发生了什么 | What happened
租户dev，有3个帐户，其中一个账户欠费，已经是封锁状态，在门户的作业界面和命令行还是可以提交作业。
并且在用户账户封锁状态同步过。
<img width="866" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/2e1cc891-098a-4848-87b0-5abeb0b47d5a">

### 运行环境 | Environment

```Markdown
- OS:ubuntu-20.04
- Scheduler: slurm 23.11.0
- Docker: 24.0.7
- Docker-compose: 2.23.3
- SCOW cli: 1.2.3
- SCOW: master
- Adapter: master
```

**Comment by huangjun0210** [comment]
slurm中检查该账户是否被封锁

**Comment by liu-shaobo** [comment]
是查看该账户的MaxJobs 和 MaxSubmit 对吧？ 该账户的这两个参数没有限制。
我看文档写到，由于已封锁的账户将会在slurm集群重启后被解封，SCOW在启动时将会自动刷新一次slurm账户的封锁/解封，用户的封锁状态，同时默认在每天凌晨4点执行一次同步。
不知道为什么没有封锁？

**Comment by vanstriker** [comment]
需要参考适配器内关于封锁的定义，slurm里面怎么体现封锁，由适配器决定。

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
