### ISSUE TITLE
无法提交作业，提示用户不存在

### ISSUE THREAD

**Issue by Lemon453** [PKUHPC/SCOW#1085]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

用户表中存在这个用户但在门户系统中无法提交作业，提示内容为用户不存在（在管理节点可以提交作业）
![Uploading 1.png…]()

### 运行环境 | Environment

```Markdown
- OS:
- Scheduler:
- Docker:
- Docker-compose:
- SCOW cli:
- SCOW:
- Adapter:
```

**Comment by Lemon453** [comment]
![1](https://github.com/PKUHPC/SCOW/assets/105644839/8d023c02-1e8d-433d-820a-a82fd2260a92)

**Comment by liu-shaobo** [comment]
ldap里面有这个用户吗？ slurm里面有这个用户吗？

**Comment by Lemon453** [comment]
![2](https://github.com/PKUHPC/SCOW/assets/105644839/46025035-93f0-4b31-a532-5d22dbd5f9aa)
![3](https://github.com/PKUHPC/SCOW/assets/105644839/384aea5d-cba0-436d-af59-69aab95e7089)
![4](https://github.com/PKUHPC/SCOW/assets/105644839/e2d207cb-195c-4d16-ba2e-99e3fecc5c63)
![5](https://github.com/PKUHPC/SCOW/assets/105644839/fe4fefe3-33ad-49ac-bfeb-8e05d3f21826)

**Comment by Lemon453** [comment]
> ldap里面有这个用户吗？ldap客户端配置好了吗？ slurm里面有这个用户吗？

库里我看着是有的

**Comment by liu-shaobo** [comment]
ldap客户端配置好了没有

**Comment by Lemon453** [comment]
> ldap客户端配置好了没有

已经解决了root用户没导入

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
