### ISSUE TITLE
预定义充值类型问题

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#1134]
* mis.yaml文件
```
# 预定义的充值类型
predefinedChargingTypes:
  - 测试
```
把 "test" 改成 "测试"，为什么还显示test字段？
重启过SCOW，清空过浏览器缓存；
<img width="456" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/7564b06e-8a29-44e8-a6b9-524b5b66ad50">

### 运行环境 | Environment
```Markdown
- OS: CentOS 7.8
- Scheduler: Slurm 20.11.9
- Docker: 24.0.7
- Docker-compose: 1.25.5
- SCOW cli: v1.4.2
- SCOW: v1.4.2
- Adapter: slurm-adapter v1.5.0
```

**Comment by vanstriker** [comment]
当前版本的充值类型数据还是以数据库内的记录的数据为准
