### ISSUE TITLE
How to start the SCOW containers on local machine

### ISSUE THREAD

**Issue by adjebbar** [PKUHPC/SCOW#1142]
Hey.
I followed the installation procedures, and execute the command sudo ./cli compose up (restart), all the containers are running. The question how to access the adresses on local machine ? I tried to modifiy the config file config/clusters/hpc01/hpc01.yam and put 192.168.88.103 as in the exemple, but nothing happen?
thanks

**Comment by liu-shaobo** [comment]
Initialize using http://IP/mis
Use http://ip to access

**Comment by adjebbar** [comment]
Thnks for your answer. Where I should add this initialization?

**Comment by liu-shaobo** [comment]
web browser，such as chrome.
