### ISSUE TITLE
作业信息同步是不是写错了

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#1149]
crontab命令是不是多了一个 *
<img width="699" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/29c605bc-d0b0-48fa-8100-09718cb4aace">

* mis.yaml
```
    cron: "10 */10 * * * *"
```

### 运行环境 | Environment

```Markdown
- OS: CentOS 7.8
- Scheduler: Slurm 20.11.9
- Docker: 24.0.7
- Docker-compose: 1.25.5
- SCOW cli: v1.4.2
- SCOW: v1.4.2
- Adapter: slurm-adapter v1.5.0
```

**Comment by tongchong** [comment]
前面多了一个10，默认应该是10分钟一次：*/10 * * * *
