### ISSUE TITLE
SCOW image

### ISSUE THREAD

**Issue by adjebbar** [PKUHPC/SCOW#1151]
Hey there.
Is the docker SCOW image or the vagrant one suitable for productionnal use?
Is there like automated script that can deploy to remote cloud? like Azur...

Thanks

**Comment by vanstriker** [comment]
Hello.

We use docker SCOW image in production, the vagrant one is for trail and development.
We only have scow-cli tool for local server dployement at this time.

**Comment by adjebbar** [comment]
Could you please give me the link to and steps to install the SCOW docker image If possible in english? I would like to deploy it on cloud server. Thnaks

**Comment by vanstriker** [comment]
This is SCOW document, https://pkuhpc.github.io/SCOW/. 
You can follow steps here https://pkuhpc.github.io/SCOW/docs/category/%E5%AE%89%E8%A3%85.
You can using some tools provided by browser to translate the whole pages to english .
