### ISSUE TITLE
web控制台提交作业的问题

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#1157]
* 通过web控制台提交作业，使用命令"srun -n 2 hostname"，错误日志如下：
```
srun: error: Unable to create step for job 65: More processors requested than permitted
```
<img width="1042" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/971328fd-f84d-4296-acae-948ae2a91f03">
* 命令行提交没有问题
<img width="291" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/528b9900-da05-4dd4-9020-6432001dcbcd">

### web控制台提交作业好像不能识别SLURM_NPROCS变量
* 通过web控制台提交作业，使用命令"srun -n $SLURM_NPROCS hostname"，错误日志如下：
```
srun: error: Invalid numeric value "" for --ntasks.
```

### 运行环境 | Environment
```Markdown
- OS: CentOS 7.8
- Scheduler: Slurm 20.11.9
- Docker: 24.0.7
- Docker-compose: 1.25.5
- SCOW cli: v1.4.2
- SCOW: v1.4.2  and v1.2.3
- Adapter: slurm-adapter v1.5.0
```

**Comment by vanstriker** [comment]
直接在shell里 echo $SLURM_NPROCS 有什么输出吗？

**Comment by liu-shaobo** [comment]
shell输出正常
<img width="351" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/e2f80ebf-cc87-47f4-b7b2-4e62985d94e7">

**Comment by liu-shaobo** [comment]
* 官方demo集群运行 srun -n $SLRUM_NPROCS hostname 出现
```srun: error: Invalid numeric value "" for --ntasks.```

* 官方demo集群运行 srun -n 2 hostname 
```
srun: defined options
srun: -------------------- --------------------
srun: (null)              : hpc01_cn01
srun: jobid               : 3017
srun: job-name            : job-20240312-152400
srun: nodes               : 1
srun: ntasks              : 2
srun: verbose             : 1
srun: -------------------- --------------------
srun: end of defined options
srun: jobid 3017: nodes(1):`hpc01_cn01', cpu counts: 2(x1)
srun: launch/slurm: launch_p_step_launch: CpuBindType=(null type)
srun: launching StepId=3017.0 on host hpc01_cn01, 2 tasks: [0-1]
srun: route/default: init: route default plugin loaded
srun: launch/slurm: _task_start: Node hpc01_cn01, 2 tasks started
srun: launch/slurm: _task_finish: Received task exit notification for 2 tasks of StepId=3017.0 (status=0x0000).
srun: launch/slurm: _task_finish: hpc01_cn01: tasks 0-1: Completed
```
* 自己的集群运行 srun -n 2 hostname 
好像是提交任务的单节点核心数的变量cpus-per-task这个导致，但是命令行不会出现这个问题，你可留一个邮箱，我把登陆方式给你看看；如果使用 srun -n 2 -c 1 hostname 就不会报错；
<img width="1082" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/a82376ab-ab21-43f4-97c2-23766f83e1ba">

```srun: defined options
srun: -------------------- --------------------
srun: (null)              : node001
srun: cpus-per-task       : 2
srun: jobid               : 91
srun: job-name            : job-20240312-152309
srun: mem-per-cpu         : 1G
srun: nodes               : 1
srun: ntasks              : 2
srun: verbose             : 1
srun: -------------------- --------------------
srun: end of defined options
srun: jobid 91: nodes(1):`node001', cpu counts: 2(x1)
srun: error: Unable to create step for job 91: More processors requested than permitted
```

**Comment by liu-shaobo** [comment]
看的源码里面是 **核心数** -c 取单节点核心数“--cpus-per-task”，一般sbatch脚本采用每个节点的任务数 --ntasks-per-node 或--ntasks参数更多！对于mpi任务，感觉这个参数不太合适；

**Comment by vanstriker** [comment]
slurm参数多，scow不会全部做成可选项。在实际使用中可以在命令框里写这些参数，命令框里的参数会是优先级最高的。
