### ISSUE TITLE
web端提交作业失败，报错权限不足

### ISSUE THREAD

**Issue by wangkai111111** [PKUHPC/SCOW#1173]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

![1711005686377](https://github.com/PKUHPC/SCOW/assets/74865581/4f0dd84f-d4a6-4654-8b15-65adeb643e55)

### 运行环境 | Environment

```Markdown
- OS:
- Scheduler:
- Docker:
- Docker-compose:
- SCOW cli:
- SCOW:
- Adapter:
```

**Comment by wangkai111111** [comment]
解决了

**Comment by Remielyzs** [comment]
> 解决了

你怎么解决的哥们儿
