### ISSUE TITLE
[Help] 服务节点是否可以使用计算节点，还是必须是单独的节点

### ISSUE THREAD

**Issue by reckonzzz** [PKUHPC/SCOW#1227]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

请问服务节点是否可以同时为计算节点？

### 运行环境 | Environment

```Markdown
- OS:
- Scheduler:
- Docker:
- Docker-compose:
- SCOW cli:
- SCOW:
- Adapter:
```

**Comment by vanstriker** [comment]
不建议这样操作，特别是在生产环境中

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
