### ISSUE TITLE
一个任务在数据库里面有两条消费记录

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#1354]
### 发生了什么 | What happened
一个任务在数据库里面有两条消费记录，但是在web控制台只显示了其中一条；
<img width="966" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/92bd3fd7-4de6-4f18-a706-1d429069446e">

另外相关的一个问题：如果账户没有任何作业，或作业信息没有同步，进入账户的消费记录就会出现500错误；
<img width="1108" alt="image" src="https://github.com/PKUHPC/SCOW/assets/6166167/5004b93d-6924-4056-a8d1-096dba9d66e6">

### 运行环境 | Environment

```Markdown
- OS: ubuntu 20.04
- Scheduler: 23.11.0
- Docker: 24.0.9
- Docker-compose: v2.24.1
- SCOW cli: 1.5.2
- SCOW: 1.6.1
- Adapter: 1.5
```

**Comment by vanstriker** [comment]
1、是否能稳定复现？
2、可以看下portal-server和portal-web的报错日志

**Comment by warren88888888** [comment]
您好！对于您提到的第一个问题：两条消费记录中，一条是针对平台的消费记录，一条是针对租户的消费记录，所以数据库中有两条消费记录是正常的。现在SCOW页面提供的都是账户的消费记录。感谢您的提问~
