### ISSUE TITLE
#0 366.6 Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by marconqi** [PKUHPC/SCOW#151]
Hi Developer, 

I try to run the docker build to create the image, it shows this error. I don't know how to fix it. Could you help?

My env. Ubuntu  

# docker --version
Docker version 20.10.17, build 100c701

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

Best,
Michael Qi

...
> [ghcr.io/pkuhpc/scow/portal-web-portal:latest builder 19/20] RUN pnpm run build:
#0 5.845
#0 5.845 > scow@ build /app
#0 5.845 > pnpm run -r build
#0 5.845
#0 9.468 Scope: 4 of 5 workspace projects
#0 9.498 libs/auth build$ rimraf build && tsc -p tsconfig.build.json && tsc-alias -p tsconfig.build.json
#0 9.501 libs/config build$ rimraf build && tsc -p tsconfig.build.json && tsc-alias -p tsconfig.build.json
#0 9.503 libs/decimal build$ rimraf build && tsc -p tsconfig.build.json
#0 42.40 libs/decimal build: Done
#0 45.34 libs/auth build: Done
#0 47.46 libs/config build: Done
#0 47.56 apps/portal-web build$ pnpm prepareDev && npm run build:nogen
#0 50.36 apps/portal-web build: > @scow/portal-web@0.1.0 prepareDev /app/apps/portal-web
#0 50.36 apps/portal-web build: > pnpm protos && ntar schema
#0 52.75 apps/portal-web build: > @scow/portal-web@0.1.0 protos /app/apps/portal-web
#0 52.75 apps/portal-web build: > tsgrpc-cli protos
#0 53.40 apps/portal-web build: [tsgrpc-cli] Using binPath /app/node_modules/.bin
#0 53.41 apps/portal-web build: [tsgrpc-cli] Generating protobuf files ../../protos/common/job.proto in path ../../protos. Resolved 1 files.
#0 77.47 apps/portal-web build: > @scow/portal-web@0.1.0 build:nogen
#0 77.47 apps/portal-web build: > next build
#0 80.62 apps/portal-web build: warn  - Invalid next.config.js options detected:
#0 80.62 apps/portal-web build: [
#0 80.63 apps/portal-web build:   {
#0 80.64 apps/portal-web build:     "instancePath": "",
#0 80.64 apps/portal-web build:     "schemaPath": "#/additionalProperties",
#0 80.64 apps/portal-web build:     "keyword": "additionalProperties",
#0 80.64 apps/portal-web build:     "params": {
#0 80.64 apps/portal-web build:       "additionalProperty": "webpackDevMiddleware"
#0 80.65 apps/portal-web build:     },
#0 80.65 apps/portal-web build:     "message": "must NOT have additional properties"
#0 80.65 apps/portal-web build:   },
#0 80.66 apps/portal-web build:   {
#0 80.66 apps/portal-web build:     "instancePath": "",
#0 80.66 apps/portal-web build:     "schemaPath": "#/additionalProperties",
#0 80.66 apps/portal-web build:     "keyword": "additionalProperties",
#0 80.67 apps/portal-web build:     "params": {
#0 80.68 apps/portal-web build:       "additionalProperty": "configOrigin"
#0 80.68 apps/portal-web build:     },
#0 80.68 apps/portal-web build:     "message": "must NOT have additional properties"
#0 80.69 apps/portal-web build:   },
#0 80.70 apps/portal-web build:   {
#0 80.70 apps/portal-web build:     "instancePath": "",
#0 80.70 apps/portal-web build:     "schemaPath": "#/additionalProperties",
#0 80.70 apps/portal-web build:     "keyword": "additionalProperties",
#0 80.71 apps/portal-web build:     "params": {
#0 80.71 apps/portal-web build:       "additionalProperty": "target"
#0 80.71 apps/portal-web build:     },
#0 80.71 apps/portal-web build:     "message": "must NOT have additional properties"
#0 80.71 apps/portal-web build:   },
#0 80.72 apps/portal-web build:   {
#0 80.72 apps/portal-web build:     "instancePath": "",
#0 80.72 apps/portal-web build:     "schemaPath": "#/additionalProperties",
#0 80.72 apps/portal-web build:     "keyword": "additionalProperties",
#0 80.72 apps/portal-web build:     "params": {
#0 80.73 apps/portal-web build:       "additionalProperty": "analyticsId"
#0 80.73 apps/portal-web build:     },
#0 80.73 apps/portal-web build:     "message": "must NOT have additional properties"
#0 80.73 apps/portal-web build:   },
#0 80.73 apps/portal-web build:   {
#0 80.73 apps/portal-web build:     "instancePath": "",
#0 80.73 apps/portal-web build:     "schemaPath": "#/additionalProperties",
#0 80.74 apps/portal-web build:     "keyword": "additionalProperties",
#0 80.74 apps/portal-web build:     "params": {
#0 80.74 apps/portal-web build:       "additionalProperty": "webpack5"
#0 80.74 apps/portal-web build:     },
#0 80.74 apps/portal-web build:     "message": "must NOT have additional properties"
#0 80.75 apps/portal-web build:   },
#0 80.75 apps/portal-web build:   {
#0 80.75 apps/portal-web build:     "instancePath": "",
#0 80.75 apps/portal-web build:     "schemaPath": "#/additionalProperties",
#0 80.75 apps/portal-web build:     "keyword": "additionalProperties",
#0 80.75 apps/portal-web build:     "params": {
#0 80.75 apps/portal-web build:       "additionalProperty": "svgrOptions"
#0 80.75 apps/portal-web build:     },
#0 80.75 apps/portal-web build:     "message": "must NOT have additional properties"
#0 80.75 apps/portal-web build:   },
#0 80.75 apps/portal-web build:   {
#0 80.75 apps/portal-web build:     "instancePath": "/amp/canonicalBase",
#0 80.75 apps/portal-web build:     "schemaPath": "#/properties/amp/properties/canonicalBase/minLength",
#0 80.75 apps/portal-web build:     "keyword": "minLength",
#0 80.76 apps/portal-web build:     "params": {
#0 80.76 apps/portal-web build:       "limit": 1
#0 80.76 apps/portal-web build:     },
#0 80.76 apps/portal-web build:     "message": "must NOT have fewer than 1 characters"
#0 80.76 apps/portal-web build:   },
#0 80.76 apps/portal-web build:   {
#0 80.77 apps/portal-web build:     "instancePath": "/assetPrefix",
#0 80.77 apps/portal-web build:     "schemaPath": "#/properties/assetPrefix/minLength",
#0 80.77 apps/portal-web build:     "keyword": "minLength",
#0 80.77 apps/portal-web build:     "params": {
#0 80.77 apps/portal-web build:       "limit": 1
#0 80.77 apps/portal-web build:     },
#0 80.77 apps/portal-web build:     "message": "must NOT have fewer than 1 characters"
#0 80.77 apps/portal-web build:   },
#0 80.77 apps/portal-web build:   {
#0 80.78 apps/portal-web build:     "instancePath": "/experimental/outputFileTracingRoot",
#0 80.78 apps/portal-web build:     "schemaPath": "#/properties/experimental/properties/outputFileTracingRoot/minLength",
#0 80.78 apps/portal-web build:     "keyword": "minLength",
#0 80.78 apps/portal-web build:     "params": {
#0 80.78 apps/portal-web build:       "limit": 1
#0 80.78 apps/portal-web build:     },
#0 80.78 apps/portal-web build:     "message": "must NOT have fewer than 1 characters"
#0 80.78 apps/portal-web build:   },
#0 80.78 apps/portal-web build:   {
#0 80.78 apps/portal-web build:     "instancePath": "/generateEtags",
#0 80.78 apps/portal-web build:     "schemaPath": "#/properties/generateEtags/isFunction",
#0 80.78 apps/portal-web build:     "keyword": "isFunction",
#0 80.78 apps/portal-web build:     "params": {},
#0 80.78 apps/portal-web build:     "message": "must pass \"isFunction\" keyword validation"
#0 80.78 apps/portal-web build:   },
#0 80.79 apps/portal-web build:   {
#0 80.79 apps/portal-web build:     "instancePath": "/i18n",
#0 80.79 apps/portal-web build:     "schemaPath": "#/properties/i18n/type",
#0 80.80 apps/portal-web build:     "keyword": "type",
#0 80.80 apps/portal-web build:     "params": {
#0 80.80 apps/portal-web build:       "type": "object"
#0 80.80 apps/portal-web build:     },
#0 80.80 apps/portal-web build:     "message": "must be object"
#0 80.80 apps/portal-web build:   }
#0 80.80 apps/portal-web build: ]
#0 80.80 apps/portal-web build: See more info here: https://nextjs.org/docs/messages/invalid-next-config
#0 80.80 apps/portal-web build: Attention: Next.js now collects completely anonymous telemetry regarding usage.
#0 80.80 apps/portal-web build: This information is used to shape Next.js' roadmap and prioritize features.
#0 80.80 apps/portal-web build: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#0 80.80 apps/portal-web build: https://nextjs.org/telemetry
#0 82.06 apps/portal-web build: info  - Linting and checking validity of types...
#0 93.46 apps/portal-web build: warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
#0 93.83 apps/portal-web build: Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .
#0 166.1 apps/portal-web build: info  - Creating an optimized production build...
#0 189.3 apps/portal-web build: <w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving 'undici/lib/llhttp/llhttp_simd.wasm' in /app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib for build dependencies doesn't lead to expected result '/app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/llhttp/llhttp_simd.wasm.js', but to '/app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/llhttp/llhttp_simd.wasm' instead. Resolving dependencies are ignored for this path.
#0 189.3 apps/portal-web build: <w>  at unknown 4 undici/lib/llhttp/llhttp_simd.wasm
#0 189.3 apps/portal-web build: <w>  at file dependencies /app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/client.js
#0 189.3 apps/portal-web build: <w>  at file /app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/client.js
#0 189.3 apps/portal-web build: <w>  at file dependencies /app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/agent.js
#0 189.3 apps/portal-web build: <w>  at file /app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/agent.js
#0 189.3 apps/portal-web build: <w>  at file dependencies /app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/proxy-agent.js
#0 189.3 apps/portal-web build: <w>  at file /app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/proxy-agent.js
#0 189.3 apps/portal-web build: <w>  at file dependencies /app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/index.js
#0 189.3 apps/portal-web build: <w>  at file /app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/index.js
#0 189.3 apps/portal-web build: <w>  at file dependencies /app/libs/auth/build/validateToken.js
#0 189.3 apps/portal-web build: <w>  at file /app/libs/auth/build/validateToken.js
#0 189.3 apps/portal-web build: <w>  at file dependencies /app/libs/auth/build/index.js
#0 189.3 apps/portal-web build: <w>  at file /app/libs/auth/build/index.js
#0 189.3 apps/portal-web build: <w>  at file dependencies /app/apps/portal-web/config.js
#0 189.3 apps/portal-web build: <w>  at file /app/apps/portal-web/config.js
#0 189.3 apps/portal-web build: <w>  at file dependencies /app/apps/portal-web/next.config.js
#0 189.3 apps/portal-web build: <w>  at file /app/apps/portal-web/next.config.js
#0 189.3 apps/portal-web build: <w>  at resolve commonjs /app/apps/portal-web/next.config.js
#0 366.6 Cannot read properties of undefined (reading 'slice')
#0 368.8  ELIFECYCLE  Command failed with exit code 1.
------
failed to solve: executor failed running [/bin/sh -c pnpm run build]: exit code: 1

**Comment by ddadaal** [comment]
Hello!

We have a `dev/docker-compose.build.yml` to build the project. Would you like to build images using the file by running the following command and see if the error persists?

```bash
docker compose -f dev/docker-compose.build.yml build 
```

BTW I am doing a refactor for the project right now, which may involve the docker image build process. I will comment here again when the refactor is done, and you might try again at that time.

**Comment by marconqi** [comment]
Hi Junda,

I will try later. The command I used is the one you suggested.

Best,
Michael

**Comment by ddadaal** [comment]
Hello. Please try building the project again. I have tested the build on an exactly identical environment (ubuntu 20.04 and docker 20.10.17) with a clean clone and it works fine.

**Comment by marconqi** [comment]
Hi Junda,

Thanks for your reply.

But I got this error message, the blue line are the commands:

# git clone https://github.com/PKUHPC/SCOW.git
Cloning into 'SCOW'...
remote: Enumerating objects: 10753, done.
remote: Counting objects: 100% (501/501), done.
remote: Compressing objects: 100% (252/252), done.
remote: Total 10753 (delta 251), reused 434 (delta 232), pack-reused 10252
Receiving objects: 100% (10753/10753), 7.13 MiB | 6.60 MiB/s, done.
Resolving deltas: 100% (7194/7194), done.
# cd SCOW/
# ls
README.md  commitlint.config.js  dockerfiles  libs          pnpm-lock.yaml
      protos         tsconfig.json
apps       dev                   docs         package.json
 pnpm-workspace.yaml  renovate.json
# export IMAGE_BASE=ghcr.io/pkuhpc/scow
# export TAG=latest
# docker compose -f dev/docker-compose.build.yml build
[+] Building 6.8s (57/236)
 => [ghcr.io/pkuhpc/scow/mis-web-mis:latest internal] load build definition
from Dockerfile.mis-web                     0.0s
 => => transferring dockerfile: 2.27kB
                                             0.0s
 => [ghcr.io/pkuhpc/scow/mis-server:latest internal] load build definition
from Dockerfile.mis-server                   0.0s
 => => transferring dockerfile: 2.10kB
                                             0.0s
 => [ghcr.io/pkuhpc/scow/mis-web-root:latest internal] load build
definition from Dockerfile.mis-web                    0.1s
 => => transferring dockerfile: 2.27kB
                                             0.0s
 => [ghcr.io/pkuhpc/scow/portal-web-root:latest internal] load build
definition from Dockerfile.portal-web              0.1s
 => => transferring dockerfile: 2.67kB
                                             0.0s
 => [ghcr.io/pkuhpc/scow/portal-web-portal:latest internal] load build
definition from Dockerfile.portal-web            0.1s
 => => transferring dockerfile: 2.67kB
                                             0.0s
 => [ghcr.io/pkuhpc/scow/auth:latest internal] load build definition from
Dockerfile.auth                               0.3s
 => => transferring dockerfile: 1.30kB
                                             0.0s
 => [ghcr.io/pkuhpc/scow/gateway:latest internal] load build definition
from Dockerfile.gateway                         0.2s
 => => transferring dockerfile: 735B
                                             0.0s
 => [ghcr.io/pkuhpc/scow/mis-web-mis:latest internal] load .dockerignore
                                             0.1s
 => => transferring context: 102B
                                            0.0s
 => [ghcr.io/pkuhpc/scow/mis-server:latest internal] load .dockerignore
                                            0.1s
 => => transferring context: 102B
                                            0.0s
 => [ghcr.io/pkuhpc/scow/mis-web-root:latest internal] load .dockerignore
                                            0.2s
 => => transferring context: 102B
                                            0.0s
 => [ghcr.io/pkuhpc/scow/portal-web-root:latest internal] load
.dockerignore                                            0.3s
 => => transferring context: 102B
                                            0.0s
 => [ghcr.io/pkuhpc/scow/gateway:latest internal] load .dockerignore
                                             0.2s
 => => transferring context: 102B
                                            0.0s
 => [ghcr.io/pkuhpc/scow/portal-web-portal:latest internal] load
.dockerignore                                          0.2s
 => => transferring context: 102B
                                            0.0s
 => [ghcr.io/pkuhpc/scow/auth:latest internal] load .dockerignore
                                            0.3s
 => => transferring context: 102B
                                            0.0s
 => [ghcr.io/pkuhpc/scow/auth:latest internal] load metadata for
***@***.***:19085641  6.6s
 => [ghcr.io/pkuhpc/scow/mis-web-mis:latest internal] load build context
                                             0.2s
 => => transferring context: 1.23MB
                                            0.1s
 => [ghcr.io/pkuhpc/scow/portal-web-root:latest runner  1/20] FROM
***@***.***:190856  0.1s
 => => resolve
***@***.***:1908564153449b1c46b329e6ce2307e226bc566294f822f11c5a8bcef4
 0.0s
 => [ghcr.io/pkuhpc/scow/mis-server:latest internal] load build context
                                            0.1s
 => => transferring context: 941.41kB
                                            0.1s
 => [ghcr.io/pkuhpc/scow/mis-web-root:latest internal] load build context
                                            0.2s
 => => transferring context: 1.23MB
                                            0.1s
 => [ghcr.io/pkuhpc/scow/gateway:latest internal] load metadata for
***@***.***:9c2030e1ff2c  0.0s
 => [ghcr.io/pkuhpc/scow/portal-web-portal:latest internal] load build
context                                          0.2s
 => => transferring context: 1.21MB
                                            0.1s
 => CACHED [ghcr.io/pkuhpc/scow/portal-web-root:latest runner  2/25] RUN
apk add --no-cache openssh-client              0.0s
 => CACHED [ghcr.io/pkuhpc/scow/portal-web-root:latest runner  3/25]
WORKDIR /app                                       0.0s
 => [ghcr.io/pkuhpc/scow/gateway:latest 1/4] FROM
***@***.***:9c2030e1ff2c3fef7440a7fb694755  0.0s
 => => resolve
***@***.***:9c2030e1ff2c3fef7440a7fb69475553e548b9685683bdbf669ac0829b889d5f
  0.0s
 => [ghcr.io/pkuhpc/scow/gateway:latest internal] load build context
                                             0.1s
 => => transferring context: 1.54kB
                                            0.0s
 => [ghcr.io/pkuhpc/scow/auth:latest internal] load build context
                                            0.1s
 => => transferring context: 3.61MB
                                            0.0s
 => [ghcr.io/pkuhpc/scow/portal-web-root:latest internal] load build
context                                            0.1s
 => => transferring context: 1.21MB
                                            0.0s
 => CACHED [ghcr.io/pkuhpc/scow/gateway:latest 2/4] RUN sed -i "1
i\load_module /etc/nginx/modules/ngx_http_js_module.  0.0s
 => CACHED [ghcr.io/pkuhpc/scow/gateway:latest 3/4] COPY
apps/gateway/includes /etc/nginx/includes                      0.0s
 => CACHED [ghcr.io/pkuhpc/scow/gateway:latest 4/4] COPY
apps/gateway/nginx.conf /etc/nginx/templates/default.conf.tem  0.0s
 => CACHED [ghcr.io/pkuhpc/scow/auth:latest builder  2/18] RUN apk update
&& apk add libc6-compat python3 make gcc g++  0.0s
 => CACHED [ghcr.io/pkuhpc/scow/auth:latest builder  3/18] RUN corepack
enable                                          0.0s
 => CACHED [ghcr.io/pkuhpc/scow/auth:latest builder  4/18] WORKDIR /app
                                            0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-web-mis:latest builder  5/18] COPY
package.json pnpm-lock.yaml pnpm-workspace.yaml  0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-web-mis:latest builder  6/18] COPY
libs/auth/package.json ./libs/auth/              0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-web-mis:latest builder  7/18] COPY
libs/config/package.json ./libs/config/          0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-web-mis:latest builder  8/18] COPY
libs/decimal/package.json ./libs/decimal/        0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-web-mis:latest builder  9/18] COPY
apps/mis-web/package.json apps/mis-web/          0.0s
 => ERROR [ghcr.io/pkuhpc/scow/mis-web-mis:latest builder 10/18] RUN pnpm i
--frozen-lockfile                           5.9s
 => [ghcr.io/pkuhpc/scow/gateway:latest] exporting to image
                                            0.2s
 => => exporting layers
                                            0.0s
 => => writing image
sha256:6184a1faae1e6fa88b665cce7c285effce3e3bd1a9fde808039f7ef7246d03de
                       0.0s
 => => naming to ghcr.io/pkuhpc/scow/gateway:latest
                                            0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-server:latest builder  5/20] COPY
package.json pnpm-lock.yaml pnpm-workspace.yaml   0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-server:latest builder  6/20] COPY
libs/config/package.json ./libs/config/           0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-server:latest builder  7/20] COPY
libs/auth/package.json ./libs/auth/               0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-server:latest builder  8/20] COPY
libs/decimal/package.json ./libs/decimal/         0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-server:latest builder  9/20] COPY
libs/ssh/package.json ./libs/ssh/                 0.0s
 => CACHED [ghcr.io/pkuhpc/scow/mis-server:latest builder 10/20] COPY
apps/mis-server/package.json ./apps/mis-server/   0.0s
 => CACHED [ghcr.io/pkuhpc/scow/portal-web-portal:latest builder  5/22]
COPY package.json pnpm-lock.yaml pnpm-workspac  0.0s
 => CACHED [ghcr.io/pkuhpc/scow/portal-web-portal:latest builder  6/22]
COPY libs/auth/package.json ./libs/auth/        0.0s
 => CACHED [ghcr.io/pkuhpc/scow/portal-web-portal:latest builder  7/22]
COPY libs/config/package.json ./libs/config/    0.0s
 => CACHED [ghcr.io/pkuhpc/scow/portal-web-portal:latest builder  8/22]
COPY libs/decimal/package.json ./libs/decimal/  0.0s
 => CACHED [ghcr.io/pkuhpc/scow/portal-web-portal:latest builder  9/22]
COPY libs/ssh/package.json ./libs/ssh/          0.0s
 => CACHED [ghcr.io/pkuhpc/scow/portal-web-portal:latest builder 10/22]
COPY apps/portal-web/package.json ./apps/porta  0.0s
 => CANCELED [ghcr.io/pkuhpc/scow/portal-web-portal:latest builder 11/22]
RUN pnpm i --frozen-lockfile                  5.7s
 => CANCELED [ghcr.io/pkuhpc/scow/mis-server:latest builder 11/20] RUN pnpm
i --frozen-lockfile                         5.9s
 => CACHED [ghcr.io/pkuhpc/scow/auth:latest builder  5/14] COPY
package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc  0.0s
 => CACHED [ghcr.io/pkuhpc/scow/auth:latest builder  6/14] COPY
libs/config/package.json ./libs/config/                 0.0s
 => CACHED [ghcr.io/pkuhpc/scow/auth:latest builder  7/14] COPY
apps/auth/package.json ./apps/auth/                     0.0s
 => CANCELED [ghcr.io/pkuhpc/scow/auth:latest builder  8/14] RUN pnpm i
--frozen-lockfile                               5.9s
------
 > [ghcr.io/pkuhpc/scow/mis-web-mis:latest builder 10/18] RUN pnpm i
--frozen-lockfile:
#0 5.747 Internal Error: Error when performing the request
#0 5.747     at ClientRequest.<anonymous>
(/usr/local/lib/node_modules/corepack/dist/corepack.js:3937:20)
#0 5.747     at ClientRequest.emit (node:events:527:28)
#0 5.747     at TLSSocket.socketErrorListener (node:_http_client:454:9)
#0 5.747     at TLSSocket.emit (node:events:527:28)
#0 5.747     at emitErrorNT (node:internal/streams/destroy:157:8)
#0 5.747     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
#0 5.747     at processTicksAndRejections
(node:internal/process/task_queues:83:21)
------
failed to solve: executor failed running [/bin/sh -c pnpm i
--frozen-lockfile]: exit code: 1


Best,
Michael

**Comment by ddadaal** [comment]
This should be a network issue. Please try again.

BTW, we do have built images hosted on github and aliyun CR. You can send an email to me (ddadaal@outlook.com) and tell me whether you can in China Mainland or not to request access to these images.

**Comment by ddadaal** [comment]
We have CI setup to test image build process. The build should be fine. Closing the issue.
