### ISSUE TITLE
MIS deployment failed. The access page displays internal server error

### ISSUE THREAD

**Issue by GuoYingLong** [PKUHPC/SCOW#174]
+ docker-compose ps 
<img width="981" alt="image" src="https://user-images.githubusercontent.com/40883280/186839381-378025b2-3466-4ca8-8c0f-9d396c75eda9.png">

+ mis-web logs

  ghcr.io/pkuhpc/scow/gateway:latest           "/docker-entrypoint.…"   4 minutes ago   Up 4 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp   scow-deployment-master-gateway-1
[root@master scow-deployment-master]# docker logs 3b68b484584a

> @scow/mis-web@0.1.0 serve
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Server Runtime Config {
  AUTH_EXTERNAL_URL: '/auth',
  AUTH_INTERNAL_URL: 'http://auth:5000',
  CLUSTERS_CONFIG: {
    '1': {
      displayName: 'aiserver',
      misIgnore: true,
      slurm: [Object],
      scheduler: 'slurm'
    }
  },
  CLUSTER_TEXTS_CONFIG: {
    default: { clusterComment: 'aiserver', extras: [Array] },
    tenant_1: { clusterComment: 'aiserver' }
  },
  UI_CONFIG: {
    footer: { defaultText: 'demo' },
    primaryColor: { defaultColor: '#9B0000' }
  },
  DEFAULT_PRIMARY_COLOR: '#9B0000',
  SERVER_URL: 'mis-server:5000'
}
Public Runtime Config {
  ENABLE_CREATE_USER: false,
  ENABLE_CHANGE_PASSWORD: false,
  PREDEFINED_CHARGING_TYPES: [ 'demo' ],
  CLUSTERS: { '1': { id: '1', name: 'aiserver' } },
  ACCOUNT_NAME_PATTERN: '',
  ACCOUNT_NAME_PATTERN_MESSAGE: 'error',
  PORTAL_URL: '/'
}
warn  - Invalid next.config.js options detected:
  - The root value has an unexpected property, webpackDevMiddleware, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
  - The root value has an unexpected property, configOrigin, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
  - The root value has an unexpected property, target, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
  - The root value has an unexpected property, webpack5, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
  - The root value has an unexpected property, svgrOptions, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
  - The value at .amp.canonicalBase must be 1 character or more but it was 0 characters.
  - The value at .assetPrefix must be 1 character or more but it was 0 characters.
  - The value at .experimental.outputFileTracingRoot must be 1 character or more but it was 0 characters.
  - The value at .i18n must be an object but it was null.

See more info here: https://nextjs.org/docs/messages/invalid-next-config
Error: 5 NOT_FOUND: Unknown Error
    at Object.callErrorFromStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.6.10/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.6.10/node_modules/@grpc/grpc-js/build/src/client.js:190:52)
    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.6.10/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.6.10/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/.pnpm/@grpc+grpc-js@1.6.10/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/.pnpm/@grpc+grpc-js@1.6.10/node_modules/@grpc/grpc-js/build/src/client.js:160:30)
    at ServiceClientImpl.getUserInfo (/app/node_modules/.pnpm/@grpc+grpc-js@1.6.10/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/.pnpm/@ddadaal+tsgrpc-utils@0.14.2_@grpc+grpc-js@1.6.10/node_modules/@ddadaal/tsgrpc-utils/lib/async.js:14:27
    at new Promise (<anonymous>)
    at asyncClientCall (/app/node_modules/.pnpm/@ddadaal+tsgrpc-utils@0.14.2_@grpc+grpc-js@1.6.10/node_modules/@ddadaal/tsgrpc-utils/lib/async.js:13:12)
    at validateToken (/app/apps/mis-web/.next/server/chunks/1536.js:475:61)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/apps/mis-web/.next/server/pages/api/auth/callback.js:136:9 {
  code: 5,
  details: 'Unknown Error',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

+ mis-server log

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/40883280/186840593-f1eb3142-fb67-4949-b747-37724dae923a.png">

**Comment by GuoYingLong** [comment]
+ Browser access prompt


<img width="1435" alt="image" src="https://user-images.githubusercontent.com/40883280/186840834-fe88da7b-99ac-4e83-b566-9a1a2eb0c05f.png">

**Comment by ddadaal** [comment]
Hello. This is because the user you are logging in with doesn't exist in the MIS db. Please check whether there is a user in the scow db with the same user id (the `userId` column of the `user` table) as the one you are logging in with. 

You can access db by executing the `db.sh` script located at the root of `scow-deployment` folder. If there is no such file, please `git pull` at the `scow-deployment` project to get the latest version.

**Comment by GuoYingLong** [comment]
I tried to update the data table, but I still couldn't log in after the update
