### ISSUE TITLE
部署文档

### ISSUE THREAD

**Issue by xxw1999** [PKUHPC/SCOW#325]
我们的部署文档有跟据代码提交而更新吗
$  ./compose.sh up -d
log dir already exists!
docker-compose.json and db.sh generated successfully!
Pulling gateway (ghcr.io/pkuhpc/scow/gateway:master)...
ERROR: Head https://ghcr.io/v2/pkuhpc/scow/gateway/manifests/master: unauthorized

**Comment by ddadaal** [comment]
有的。当前系统需要自己从源码构建，暂不提供编译好的镜像，请根据文档构建镜像：https://pkuhpc.github.io/SCOW/docs/common/deployment#%E4%BB%8E%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BA

**Comment by xxw1999** [comment]
我是按照部署执行的  构建成功了

**Comment by ddadaal** [comment]
config.py中的COMMON.IMAGE_BASE和IMAGE_TAG需要和构建时的dev/.dev.build中指定的IMAGE_BASE和IMAGE_TAG对应。我发现目前默认的构建时的tag为latest，但是默认的config.py中为master，不匹配。我会立刻修复这个目前。目前您可以先修改config.py中的COMMON.IMAGE_TAG为latest来临时解决一下。

**Comment by xxw1999** [comment]
![image](https://user-images.githubusercontent.com/68838115/204726508-855a411a-b0f8-4c8b-97f5-8378da73d103.png)
想简单问一下   好几个容器起不来都报的这个错误，但是配置项密码我用的默认的，是怎么回事呢

**Comment by ddadaal** [comment]
这里的报错是集群配置文件中的slurm.mis.dbPassword的问题。您的密码这个项是不是纯数字组成的？如果是的话，在yaml中纯数字的值会被解析为数字，您需要把这个值用引号包裹起来：

```yaml
dbPassword: 12345678 # 这会被解析为数字
dbPassword: "12345678" # 这才是字符串
```
