### ISSUE TITLE
Invalid documentation links in README.md

### ISSUE THREAD

**Issue by weijianwen** [PKUHPC/SCOW#361]
The following documentation links are invalid. Much appreciated if they are pointed to the correct docs.

- https://pkuhpc.github.io/SCOW/docs/common/deployment
- https://pkuhpc.github.io/SCOW/docs/common/dev

**Comment by ddadaal** [comment]
Thanks! We just had a big doc site overhaul and unfortunately missed the links in README. #362 will fix this issue.
