### ISSUE TITLE
用源码构建好docker镜像后无法启动系统

### ISSUE THREAD

**Issue by Tangent-90C** [PKUHPC/SCOW#440]
按照这篇[文档](https://pkuhpc.github.io/SCOW/docs/deploy/SCOW)构建了SCOW的镜像后，输入`./compose.sh up -d`会报错，提示`Error response from daemon: Head "https://ghcr.io/v2/pkuhpc/scow/portal-web/manifests/master": unauthorized`，也不知道是什么原因导致的。
![image](https://user-images.githubusercontent.com/28804414/215406902-d7cf276d-1f8f-4dc0-bd24-a0b67e6fa1e3.png)

下面是我docker里的镜像，其中有部分镜像就是刚才编译出来的。
![image](https://user-images.githubusercontent.com/28804414/215406712-84a7c445-d37a-41ec-9f52-ee8e8d492cb2.png)

**Comment by ddadaal** [comment]
感谢发现这个BUG!！

这个的原因是之前我们修改不同的base path需要重新编译镜像，所以在构建镜像的时候会预先构建几个不同的base path的镜像（mis-web-root, mis-web-mis, portal-web-root, portal-web-portal这几个）。但是在#435 之后，修改base path无需重新构建镜像，所以web的镜像名就直接改成了mis-web, portal-web，但是构建脚本忘记改了。

马上修改这里，非常感谢！

**Comment by ddadaal** [comment]
重新拉取master分支并构建镜像即可。
