### ISSUE TITLE
系统初始化导入用户数目过多时会出现404错误

### ISSUE THREAD

**Issue by lyl-available** [PKUHPC/SCOW#573]
环境：62测试集群
步骤：
1、进入初始化页面，选择11个账户，共1000k以上用户，点击导入
2、提示导入成功，之后再次获取用户列表时，接口返回404，日志未返回error

![Image](https://user-images.githubusercontent.com/125553919/233294307-9aba7886-6b8c-457d-8ba3-dae191df5c6b.png)

**Comment by qhqhqhq** [comment]
![Image](https://user-images.githubusercontent.com/98016770/233302404-c2a3ea99-e581-4b58-b8a3-cfefe435929b.png)

应该是又超时了，gateway里可以看到报错。

这个不是业务逻辑问题，是执行时间太长了，当请求时间超过1分钟就会超时

**Comment by lyl-available** [comment]
> ![Image](https://user-images.githubusercontent.com/98016770/233302404-c2a3ea99-e581-4b58-b8a3-cfefe435929b.png)
> 
> 应该是又超时了，gateway里可以看到报错。
> 
> 这个不是业务逻辑问题，是执行时间太长了，当请求时间超过1分钟就会超时

我们把超时时间都改了还会报错吗？

**Comment by qhqhqhq** [comment]
现在已经改过超时时间了吗？但是这里确实是因为超时引起的

**Comment by qhqhqhq** [comment]
我简单测试了一下，当初始状态为空的时候，getclusterusers这个接口刚好花了大约58秒的时间，后续把用户导入后，读取数据库又多花了一些时间，导致超过了1分钟，所以就报错了

**Comment by lyl-available** [comment]
> 现在已经改过超时时间了吗？但是这里确实是因为超时引起的

是的，超时时间已经改过了，这个报错log时间对不上，我是今天下午测的，不是早上8点多

**Comment by lyl-available** [comment]
> 我简单测试了一下，当初始状态为空的时候，getclusterusers这个接口刚好花了大约58秒的时间，后续把用户导入后，读取数据库又多花了一些时间，导致超过了1分钟，所以就报错了
> 
> 现在这个接口慢的问题等到调度器适配器弄好应该可以缓解很多

也是报404？

**Comment by qhqhqhq** [comment]
上面那个报错信息是我刚才测的，时间显示八点多应该是时区问题，我刚才测试也是报404，就是这个issue的问题

**Comment by lyl-available** [comment]
> 上面那个报错信息是我刚才测的，时间显示八点多应该是时区问题，我刚才测试也是报404，就是这个issue的问题

emmm那就说明我们之前改的超时时间没起作用了
