### ISSUE TITLE
平台和租户历史价格显示交错

### ISSUE THREAD

**Issue by lyl-available** [PKUHPC/SCOW#574]
步骤：
1、平台管理界面，修改作业价格表

![Image](https://user-images.githubusercontent.com/125553919/233334105-9a661b10-60b7-4f04-bb54-e88af003c1a1.png)

![Image](https://user-images.githubusercontent.com/125553919/233334271-fb85e22e-f1fa-41bc-a93e-18f57f026720.png)

2、跳转至租户管理-作业价格表页面，平台作业修改记录显示在租户历史价格中

![Image](https://user-images.githubusercontent.com/125553919/233335064-fe6b258a-6391-4f91-95d0-754b5aeeb227.png)

**Comment by ddadaal** [comment]
这个行为是正确的。因为这个租户自己定义了自己的计费项，所以平台改平台默认的就不会影响这个计费项了。

看起来应该在列出租户的价格项的时候，应该忽略平台的计费项。看看在HTTP API层过滤一下。

开个新PR。

**Comment by lyl-available** [comment]
> 这个行为是正确的。因为这个租户自己定义了自己的计费项，所以平台改平台默认的就不会影响这个计费项了。

没太理解这句话，平台的计费项有修改，平台的历史计费和当前计费都会同步到租户的历史计费里，这个行为是正常的吗？平台和租户的计费规则不是完全隔开的吗？

**Comment by ddadaal** [comment]
不是完全隔开的。如果租户没有对一个计费项设置价格，那么给这个租户计费的时候就会用平台的计费项。设置了之后就会用租户自己设置的了。

**Comment by lyl-available** [comment]
> 不是完全隔开的。如果租户没有对一个计费项设置价格，那么给这个租户计费的时候就会用平台的计费项。设置了之后就会用租户自己设置的了。

噢，了解了~ 使用的计费项没有问题，是历史计费的显示要改一下，不然如果用户只是租户管理员，历史计费突然多了其他的修改记录就会很奇怪
