### ISSUE TITLE
windows环境  pnpm prepareDev 报错

### ISSUE THREAD

**Issue by Wizarddm** [PKUHPC/SCOW#653]
$ pnpm prepareDev
> scow@0.6.0 prepareDev C:\Users\86137\code\SCOW
> pnpm build:libs && turbo run prepareDev

> scow@0.6.0 build:libs C:\Users\86137\code\SCOW
> turbo run build --filter "./libs/**"

 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at C:\Users\86137\AppData\Local\Temp\turbod\2797855d8ca1bc78\turbod.pid is not running, and remove C:\Users\86137\AppData\Local\Temp\turbo
d\2797855d8ca1bc78\turbod.pid
        - check the logs at C:\Users\86137\AppData\Roaming\turborepo\data\logs\2797855d8ca1bc78-SCOW.log
        - the unix domain socket at C:\Users\86137\AppData\Local\Temp\turbod\2797855d8ca1bc78\turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
• Packages in scope: @scow/config, @scow/lib-auth, @scow/lib-config, @scow/lib-decimal, @scow/lib-hook, @scow/lib-server, @scow/lib-slurm, @scow/lib-ssh, @scow/lib-web, @scow/protos, @scow/utils
• Running build in 11 packages
• Remote caching disabled
@scow/protos:generate: cache miss, executing 62bef9df1a05e99d
@scow/lib-decimal:build: cache hit, replaying output fe7bc45d1cf92fe2
@scow/lib-decimal:build: 
@scow/lib-decimal:build: > @scow/lib-decimal@0.2.0 build C:\Users\86137\code\SCOW\libs\decimal
@scow/lib-decimal:build: > rimraf build && tsc -p tsconfig.build.json
@scow/lib-decimal:build: 
@scow/lib-ssh:build: cache hit, replaying output c7d9487460b27a4c
@scow/lib-ssh:build: 
@scow/lib-ssh:build: > @scow/lib-ssh@0.3.0 build C:\Users\86137\code\SCOW\libs\ssh
@scow/lib-ssh:build: > rimraf build && tsc -p tsconfig.build.json
@scow/lib-ssh:build: 
@scow/utils:build: cache hit, replaying output fa0d64d00cf850e4
@scow/lib-config:build: cache hit, replaying output 700b7456f479b13b
@scow/lib-config:build: 
@scow/lib-auth:build: cache hit, replaying output 1ec74054a1bcafc9
@scow/utils:build: 
@scow/lib-auth:build: 
@scow/lib-auth:build: > @scow/lib-auth@0.2.0 build C:\Users\86137\code\SCOW\libs\auth
@scow/lib-auth:build: > rimraf build && tsc -p tsconfig.build.json && tsc-alias -p tsconfig.build.json
@scow/lib-auth:build: 
@scow/utils:build: > @scow/utils@0.1.2 build C:\Users\86137\code\SCOW\libs\utils
@scow/utils:build: > rimraf build && tsc -p tsconfig.build.json
@scow/lib-config:build: > @scow/lib-config@0.2.2 build C:\Users\86137\code\SCOW\libs\libconfig
@scow/lib-config:build: > rimraf build && tsc -p tsconfig.build.json && tsc-alias -p tsconfig.build.json
@scow/lib-config:build: 
@scow/utils:build: 
@scow/config:build: cache miss, executing e4e7580726856bd9
@scow/lib-web:build: cache miss, executing 813c0d5726bbd080
@scow/protos:generate: 
@scow/protos:generate: > @scow/protos@0.2.2 generate C:\Users\86137\code\SCOW\libs\protos
@scow/protos:generate: > rimraf generated && buf generate --template buf.gen.yaml node_modules/@scow/grpc-api
@scow/protos:generate: 
@scow/lib-web:build: 
@scow/lib-web:build: > @scow/lib-web@0.3.2 build C:\Users\86137\code\SCOW\libs\web
@scow/lib-web:build: > rimraf build && tsc -p tsconfig.build.json && tsc-alias -p tsconfig.build.json
@scow/lib-web:build: 
@scow/config:build: 
@scow/config:build: > @scow/config@0.3.0 build C:\Users\86137\code\SCOW\libs\config
@scow/config:build: > rimraf build && tsc -p tsconfig.build.json && tsc-alias -p tsconfig.build.json
@scow/config:build: 
@scow/protos:generate: Failure: plugin ts-proto: exec: "node_modules/ts-proto/protoc-gen-ts_proto": file does not exist
@scow/protos:generate:  ELIFECYCLE  Command failed with exit code 1.
@scow/protos:generate: ERROR: command finished with error: command (C:\Users\86137\code\SCOW\libs\protos) pnpm run generate exited (1)
command (C:\Users\86137\code\SCOW\libs\protos) pnpm run generate exited (1)

 Tasks:    5 successful, 8 total
Cached:    5 cached, 8 total
  Time:    9.854s

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by ddadaal** [comment]
可能和Windows下symlink有关。pnpm是把ts-proto以symlink的方式链接到libs/protos/node_modules下的。请先尝试使用dev container或者Linux开发环境。
