### ISSUE TITLE
想问一下我把工程导入到webstorm后，执行npm install后还是有好多包报红找不到

### ISSUE THREAD

**Issue by hellozzcy** [PKUHPC/SCOW#673]
例如apps/portal-server/src/services/shell.ts中的import { ShellServiceServer, ShellServiceService } from "@scow/protos/build/portal/shell";这个@scow/protos/build/portal/shell就报红找不到 请问下如何解决

**Comment by ddadaal** [comment]
还需要运行`pnpm prepareDev`，文档：https://pkuhpc.github.io/SCOW/docs/contribution/dev#%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91
