### ISSUE TITLE
计费问题

### ISSUE THREAD

**Issue by liusirtothetop** [PKUHPC/SCOW#816]
你好，有两个问题需要请教，
问题一：在已结束的作业下面可以看到每个账户的平台计费。但是在账户管理下中的账户列表中的账户余额并没有减少，也就是说scow的数据库中的账户余额没有更新，是哪里出了问题，该怎么解决呢？
问题二：在已结束作业下，租户计费都是0 ，而平台计费不为0，这俩存在什么联系呢？

**Comment by ddadaal** [comment]
平台计费是指平台对作业所在租户扣的费用，扣的是租户的余额；租户计费是指租户对账户扣的费用，扣的是账户的余额。两张价格表不一样：平台管理员可以设置平台计费的价格表（/mis/admin/jobBilling），租户管理员可以设置对租户所在账户的价格表。看起来您是只设置了平台计费的表格表而没有在租户中设置账户的价格表，所以造成平台计费不为0，而租户计费为0的情况。

**Comment by liusirtothetop** [comment]
感谢您的回答，那问题一该怎么解决呢？

**Comment by vanstriker** [comment]
使用的是scow哪个版本？

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
