### ISSUE TITLE
建议创建交互式应用时分区的选择做成可配置的

### ISSUE THREAD

**Issue by lingbozeng** [PKUHPC/SCOW#832]
目前创建交互式应用时可以选择集群中的所有可用分区队列，由于集群中可能存在A分区可以使用vscode、jupyter，而B分区可以使用matlab、vscode，这时如果用户选择了B分区创建jupyter就会失败，所以，建议修改成可以在交互式应用配置文件中配置可创建交互式应用的分区名列表，然后在创建交互式应用表单里渲染出这个配置的分区列表供选择，而不是渲染出所有可用的分区。

**Comment by piccaSun** [comment]
@vanstriker 请确认这个可以直接修改吗？

如果修改考虑在各个交互式应用配置文件中添加可选配置变量后在表单进行筛选
availablePartitions?: 
   cluster?: xxx
   partitions : aaa, bbb

**Comment by vanstriker** [comment]
改成增加一个配置项，availablePartitions，没配置的话就全部可以用

**Comment by vanstriker** [comment]
@lingbozeng 这个需求现在有遇到过？

**Comment by lingbozeng** [comment]
@vanstriker 现在还没遇到这需求，主要是考虑到不同分区直接可能存在OS和系统环境有差异的问题
