### ISSUE TITLE
建议ldap用户目录支持更多灵活字段

### ISSUE THREAD

**Issue by zzb23** [PKUHPC/SCOW#853]
当前，ldap创建用户时，homeDir只能使用 {{ userId }} 一个灵活字段，无法适应不同超算中心的目录层级结构，希望能增加其它字段。

![image](https://github.com/PKUHPC/SCOW/assets/28723144/184d9f45-f127-417b-b35b-266173793e64)

![image](https://github.com/PKUHPC/SCOW/assets/28723144/44da204d-731a-41de-8dda-60a25a7a6f1e)

我们的目录层级为 /lustre/home/{{ accountName }}/{{ userId }}

可能需要改动“创建用户”的页面设计，传入更多的一些参数
![image](https://github.com/PKUHPC/SCOW/assets/28723144/90d8df89-1375-43fa-9467-c0590458bb74)

**Comment by vanstriker** [comment]
建议采用自定义认证系统和scow插件实现个性化创建用户界面。
