### ISSUE TITLE
建议ldap创建用户时能支持“同一Account下的用户能增加至同一组”

### ISSUE THREAD

**Issue by zzb23** [PKUHPC/SCOW#854]
当前ldap创建新用户时，只支持两种策略：newGroupPerUser、oneGroupForAllUsers

![image](https://github.com/PKUHPC/SCOW/assets/28723144/fb3d1c68-79c3-4c1c-a743-c47b597650b2)

希望能增加一个新的策略 `oneGroupForAccountUsers`，能够把同一账号下的用户归到同一组。

该改动可能需要在“创建用户”页传入更多参数。

**Comment by vanstriker** [comment]
建议采用自定义认证系统和scow插件实现个性化创建用户界面。
