### ISSUE TITLE
建议增加更多存储相关的功能

### ISSUE THREAD

**Issue by zzb23** [PKUHPC/SCOW#855]
当前SCOW与存储相关的功能较少，希望能够支持更多存储配额、计费相关的功能。

我们的使用场景比较复杂，为：

  - 中心存在两套集群、3套存储，/lustre、/gpfs、/archive
  - 两套集群的登录节点分别挂载了/lustre、/gpfs，另有一个data节点挂载了3套存储，专用于多套存储间的数据传输
  - 创建用户时，能在每套存储上创建用户目录，层级为 %H/home/{{ accountName }}/{{ userId }}，并分别设置默认存储配额
  - 每套存储支持修改存储配额，包括账户和用户两个层面的配额
  - 每套存储每日统计用量，主要是账户层面的用量，进行计费
  - /lustre、/gpfs使用相同的计费策略，共享3TB 免费容量，超出计费
  - /archive使用独立的计费策略，独享3TB免费容量，超出计费
  - 计费策略：每套存储一个基础单价，<3T容量免费，>10TB容量打8折等

不知道有没有好的建议或实现方案能够满足这个需求？

我们考虑的一种方案是：
- 把/lustre、/gpfs、/archive在scow上配置为3套集群的存储（即把data节点也假定为一个登录节点，根目录是/archive）
- 每套集群配置一个storages信息，指定对应的存储，包括存储名、类别、容量等
- slurm.sh增加存储配额设置的函数，每种类型存储对应一个函数，创建完新用户执行对应的配额设置
- 存储计费相关的能力参考作业计费方式实现

![image](https://github.com/PKUHPC/SCOW/assets/28723144/97d468c5-e79f-42d1-b7d6-cc23b3dd1a38)

![image](https://github.com/PKUHPC/SCOW/assets/28723144/728c6528-cfbe-4239-92d3-e433e798cf76)

以上措施应该可满足新用户在每套存储自动创建目录、设置配额，每套存储每日计费等通用需求。

但对于我们存在的难点是“如何设计能够使/lustre，/gpfs共享免费容量”（可能的方案：scow中把两套存储配置在同一集群？）

希望能够和你们进行交流，得到指导，在scow中增加更多存储计费相关功能，谢谢！

zhangzb@sjtu.edu.cn

**Comment by vanstriker** [comment]
您好，感谢建议！SCOW的核心是把算力中心通用的功能加入到系统中，同时通过强大的扩展性满足每个算力中心的个性化需求。您前面提到的需求，我们在考虑把存储配额的管理功能做到SCOW中；创建用户、存储计费等功能，因为每个算力中心的需求会差得比较多，我们现在的做法和建议是，基于SCOW的Hook和API机制，通过外部系统实现这些个性化需求。

**Comment by vanstriker** [comment]
无更新反馈，关闭issue
