### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by safeAndSound3** [PKUHPC/SCOW#881]
[IMG_1572](https://github.com/PKUHPC/SCOW/assets/146302624/8bed5b98-42b5-413c-9454-9e85af8cc326)
![IMG_1573](https://github.com/PKUHPC/SCOW/assets/146302624/31c6a3b7-8e31-4d57-b6b1-144a2cb1ba98)
图一与图二的slurm是否冲突  如果不部署slurm集群 是否所有节点都需要配置适配器

**Comment by safeAndSound3** [comment]
![IMG_1572](https://github.com/PKUHPC/SCOW/assets/146302624/82b02f7c-1368-4b71-8e1b-b684e8e3d6a0)
![IMG_1573](https://github.com/PKUHPC/SCOW/assets/146302624/716d30d1-99cb-47bd-8cb6-393bcc3b1be8)

**Comment by huangjun0210** [comment]
不冲突，SCOW是用于管理超算集群的，需要至少有一个集群来管理，例如slurm或是其他的。
SCOW支持多种不同的调度器如Slurm、CraneSched、K8S等。
如果需要管理的集群是slurm，就需要在管理节点部署slurm适配器，如果是其他的，就部署其他的适配器

**Comment by safeAndSound3** [comment]
非常感谢您能回复我的问题。这个问题我已经解决，我现在遇到了新的问题 可以帮忙排查一下么
https://github.com/PKUHPC/SCOW/discussions/885
[https://opengraph.githubassets.com/0a14e83f4076577a4ee87e170b3da386ee590fd8c2272ce938807b593c90cb70/PKUHPC/SCOW/discussions/885]<https://github.com/PKUHPC/SCOW/discussions/885>
ssh认证登录问题 ・ PKUHPC/SCOW ・ Discussion #885<https://github.com/PKUHPC/SCOW/discussions/885>
我是用的ssh认证，服务和登录节点为一台服务器，登录系统的方式是 服务器的root及密码么 登录并没有报错 但是又重定向到了/ 希望可以获得帮助 @fuzhenxin @piccaSun @ddadaal 非常感谢
github.com

我配置了ssh登录认证，初始化已经可以导入slurm的用户，但是登录遇到错误，我使用的是root的账号密码，登录后直接返回门户了
________________________________
发件人: huangjun0210 ***@***.***>
发送时间: 2023年10月11日 9:14
收件人: PKUHPC/SCOW ***@***.***>
抄送: safeAndSound3 ***@***.***>; Author ***@***.***>
主题: Re: [PKUHPC/SCOW] 部署问题 (Issue #881)


不冲突，SCOW是用于管理超算集群的，需要至少有一个集群来管理，例如slurm或是其他的。
SCOW支持多种不同的调度器如Slurm、CraneSched、K8S等。
如果需要管理的集群是slurm，就需要在管理节点部署slurm适配器，如果是其他的，就部署其他的适配器

―

**Comment by huangjun0210** [comment]
把配置文件install.yaml贴出来看看

**Comment by safeAndSound3** [comment]
# 整个系统的端口号。默认80
 port: 80

# 整个系统的部署路径。默认/
 basePath: /

# SCOW的镜像的tag。默认：master
# imageTag: master

# 门户相关配置。默认不部署
# 如果不部署，请删除或者注释整个部分
 portal:
#   # 门户路径相对于整个系统的部署路径。默认/
#   # 若设置则/开头，不要以/结尾.
#   # 如果BASE_PATH为/root1，PORTAL.BASE_PATH为/root2，那么最终访问门户系统的路径是/root1/root2
    basePath: /

#   # novnc web客户端镜像地址
#   # novncClientImage: ghcr.io/pkuhpc/novnc-client-docker:master

#   # 端口映射。如果不进行二次开发，请勿开放
#   # portMappings:
#   #   # portal-server的5000映射到。不填写则不映射
#   #   # portalServer: 127.0.0.1:7572

# 管理系统相关配置。默认不部署
# 如果不部署，请删除或者注释整个部分
 mis:
#   # 门户系统路径相对于整个系统的部署路径。默认/
#   # 若设置则/开头，不要以/结尾.
#   # 如果BASE_PATH为/root1，PORTAL.BASE_PATH为/root2，那么最终访问管理系统的路径是/root1/root2
    basePath: /mis

#   # mysql数据库的镜像地址。默认为mysql:8
#   # mysqlImage: "mysql:8"

#   # 管理系统数据库的密码。如果部署管理系统，则必须配置
#   # 第一次启动管理系统时会使用此密码初始化管理系统数据库，之后如需修改需要手动在数据库中修改
    dbPassword: "slurm0000"

#   # 端口映射。如果不进行二次开发，请勿开放
#   # portMappings:
#   #   # 数据库的3306端口映射。不填写则不映射
#   #   db: 127:0.0.1:3306
#   #   # mis-serve的5000端口映射到。不填写则不映射
#   #   misServer: 127.0.0.1:7571

# 认证系统相关配置。可选，不配置为默认配置
# auth:
#   # redis镜像。默认为redis:alpine
#     redisImage: redis:alpine

#   # 端口映射。只对内置认证系统有效
#     portMappings:
#   #   # redis的6379端口。不填写则不映射
#       redis: 127.0.0.1:6379
#   #   # 认证系统的5000端口，不填写则不映射
 #      auth: 127.0.0.1:5001

#   # 自定义认证系统。默认使用内置认证系统
#   # 如果使用内置认证系统，将此部分注释掉
#   custom:
#     # 自定义认证系统镜像名。必填
#     # image: my-custom-auth:v1.0

#     # 端口映射。可选
#     # ports:
#     #   - "5000:5000"

#     # 更多挂载卷。可选
#     # 默认添加/etc/hosts:/etc/hosts和./config:/etc/scow
#     # volumes:
#     #   - "./myfile:/etc/myfile"

#     # 环境变量，可选。
#     # environment:
#     #   - DEBUG=log

# 审计系统相关配置。默认不部署
# audit:
#   # 审计系统服务url，默认audit-server:5000
#   # url: audit-server:5000
#   # mysql数据库的镜像地址。默认为mysql:8
#   # mysqlImage: "mysql:8"
#   # 审计系统数据库的密码。如果部署审计系统，则必须配置
#   # 第一次启动审计系统时会使用此密码初始化审计系统数据库，之后如需修改需要手动在数据库中修改
#   # dbPassword: must!chang3this
#   # 端口映射。如果不进行二次开发，请勿开放
#   # portMappings:
#   #   # 数据库的3306端口映射。不填写则不映射
#   #   db: 127:0.0.1:3306
#   #   # audit-server的5000端口映射到。不填写则不映射
#   #   audit-server: 127.0.0.1:7573

# 日志相关配置
# log:
#   # 日志级别。默认info
#   # 可选：slient, error, warn, info, debug
#   level: info

#   # 是否输出更适合直接读的log。默认为false
#   # 如果为false，则输出json格式的日志。默认false
#   pretty: false

#   # fluentd日志收集服务配置。
#   # 将会使用fluent/fluent.conf作为配置文件
#   # 如果不使用，请注释整个部分
#   fluentd:
#     # fluentd镜像
#     image: fluentd:v1.14.0-1.0
#     # fluentd日志存放地点
#     logDir: /var/log/fluentd

# 网关配置
# gateway:
#   # 限制整个系统上传（请求）文件的大小。默认1G
#   # 可接受的格式为nginx的client_max_body_size可接受的值
#   uploadFileSizeLimit: 1G

#   # 限制后端服务发出响应的超时时间，默认60s
#   # 可接受的格式为nginx的proxy_read_timeout可接受的值
#   proxyReadTimeout: 60s

#   # 更多nginx配置
#   # 可接受的格式为nginx的server可接受的属性配置，例如可增加在当前系统nginx默认端口的服务
#   extra: >
#         location /extra {
#             proxy_pass http://extra-web:3000;
#             include includes/headers;
#             include includes/websocket;
#          }

# 插件配置
# plugins:
#   # 启用的插件
#   enabledPlugins: ["plugin1"]

**Comment by safeAndSound3** [comment]
[install.txt](https://github.com/PKUHPC/SCOW/files/12863955/install.txt)

**Comment by huangjun0210** [comment]
试试这个：
`port: 80
basePath: /
imageTag: v1.0.0
portal:
  portMappings: {}
mis:
  dbPassword: slurm0000
  portMappings: {}
log:
  fluentd:
    logDir: /var/log/fluentd
auth:
  portMappings: {}
audit:
  dbPassword: "must!chang3this"
gateway:
  proxyReadTimeout: 36000s
`

**Comment by huangjun0210** [comment]
试试这个：
`port: 80
basePath: /
imageTag: v1.0.0
portal:
  portMappings: {}
mis:
  dbPassword: slurm0000
  portMappings: {}
log:
  fluentd:
    logDir: /var/log/fluentd
auth:
  portMappings: {}
audit:
  dbPassword: "must!chang3this"
gateway:
  proxyReadTimeout: 36000s
`

**Comment by safeAndSound3** [comment]
好的 我试下

**Comment by safeAndSound3** [comment]
使用root的密码可以登录了，我对比了下配置文件，一个是image的tag不同，一个是网关的超时时间 其他未作修改，非常感谢
再次麻烦下，如果我想使用ldap认证，scow平台是否内置，有没有详细文档，因为我看官网提供的文档，有很多不太熟悉的地方

**Comment by huangjun0210** [comment]
加个微信沟通吧，18163650606
