### ISSUE TITLE
如何设置https链接？

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#920]
默认是通过http连接，如何设置https链接？

![image](https://github.com/PKUHPC/SCOW/assets/67989011/571cc66c-ebb9-49ab-8185-bb25f3717fde)

**Comment by zhengkang2020** [comment]
通过应用vscode 打开ipynb文件，一直加载中。

下面issue说是与https有关？https://github.com/coder/code-server/issues/5178

![image](https://github.com/PKUHPC/SCOW/assets/67989011/a82dceea-996e-41ab-aabc-d45da0c1ec81)

**Comment by huangjun0210** [comment]
SCOW暂时不支持直接配置https，如果需要使用https访问，你可以尝试在其前端使用https加一个代理(nginx).

**Comment by zhengkang2020** [comment]
好的，明白了。

通过应用vscode 打开ipynb文件，一直加载中，这个问题有遇到过吗？如何解决呢？
