### ISSUE TITLE
SCOW为什么用三级的用户模型

### ISSUE THREAD

**Issue by liu-shaobo** [PKUHPC/SCOW#924]
正常HPC门户都是账户(account)、用户(user)，也可以理解为组或用户；
SCOW为什么用三级的用户模型：租户(tenant)、账户(account)、用户(user)，感觉难以理解，增加了在系统中使用的难度。

**Comment by huangjun0210** [comment]
https://pkuhpc.github.io/SCOW/docs/info/mis/business/users

**Comment by liu-shaobo** [comment]
这个文档我看了，主要是不明白为什么要这样设计，为什么不不直接用账户(account)、用户(user)两级；
