### ISSUE TITLE
无法以用户身份连接到登录节点。请确认您的家目录的权限为700、750或者755

### ISSUE THREAD

**Issue by ZYFno996** [PKUHPC/SCOW#930]
您好，SCOW系统已经部署完成，能够正常启动、操作用户。但shell、桌面、交互式应用、文件管理几个功能均无法使用，系统横幅消息“无法以用户身份连接到登录节点。请确认您的家目录的权限为700、750或者755”。

### Shell报错
Process exited with code 1 and signal undefined.
### 桌面报错
横幅提示服务器错误500，日志报错如图
![image](https://github.com/PKUHPC/SCOW/assets/79386690/a3614b0f-14f3-4d38-8b09-311b3382752c)
### 交互式应用
进入创建页面横幅提示服务器错误500，日志报错如图
![image](https://github.com/PKUHPC/SCOW/assets/79386690/b7ba5df7-5a82-43ae-a872-257af98d29f2)
提交创建时横幅提示服务器错误500，日志报错如图
![image](https://github.com/PKUHPC/SCOW/assets/79386690/a771d231-d525-4bf5-86ce-c4be495f60c8)
### 文件管理
![image](https://github.com/PKUHPC/SCOW/assets/79386690/7fdab75b-c474-4c37-b0a7-5fb1e045490b)

config/apps/、portal..yml配置均按照文档内容填充。请问SCOW用户登录是否与login节点上的系统用户有关？在登录节点用户根目录下出现了“~用户ID”文件夹，权限为755但仍无法顺利使用上述功能。根据手册目前无法知晓哪处配置有误，以及各个子系统用户之间的关联。望解答。

**Comment by huangjun0210** [comment]
1.桌面报错看看TurboVNC是否安装？
2.其他错误主要是用户免密到登录节点不成功，检查下，
(1)scow节点到登录节点root免密;
(2)打开登录节点 `/etc/ssh/sshd_config`，添加以下内容：
`PubkeyAcceptedKeyTypes=+ssh-rsa`

# 重启 sshd
`systemctl restart sshd.service`
(3) 登录节点selinux是否已关

**Comment by ZYFno996** [comment]
> scow
1.TurboVNC在登录节点和计算节点都已安装在/opt/TurboVNC目录下
2.scow节点到登录节点和计算节点只有root用户免密
3.所有节点selinux都已关闭，getenforce显示disabled
![image](https://github.com/PKUHPC/SCOW/assets/79386690/42a5cae1-fe22-432f-8647-ac43ba67e335)
![image](https://github.com/PKUHPC/SCOW/assets/79386690/aa958e47-9c9c-419b-b0c9-dbb9a2812134)

报错中有显示"sudo: unknown user: 202021051079\nsudo: unable to initialize policy plugin"，这是否是突破口

**Comment by huangjun0210** [comment]
![image](https://github.com/PKUHPC/SCOW/assets/26295600/2fb90cf5-43c7-4a69-90b6-6fa8f8966792)
这个错误解决了没

**Comment by ZYFno996** [comment]
> ![image](https://user-images.githubusercontent.com/26295600/279556140-2fb90cf5-43c7-4a69-90b6-6fa8f8966792.png) 这个错误解决了没

重新调整ldap配置之后这个问题没有了，shell和文件管理都已恢复正常。现在的问题是：
### Error： /mis/init 页面添加初始管理员时依然报500，日志如下
![image](https://github.com/PKUHPC/SCOW/assets/79386690/c1e2d8d3-8c2f-48b4-8e4e-00fb08acb032)
### auth.yml
![image](https://github.com/PKUHPC/SCOW/assets/79386690/015250ee-f3e4-4aa9-b99f-ad23ef6797eb)

**Comment by huangjun0210** [comment]
没有uid，试试这样
```
  attrs:
    uid: uid
    name: cn
    mail: mail
```

**Comment by ZYFno996** [comment]
> 没有uid，试试这样
> 
> ```
>   attrs:
>     uid: uid
>     name: cn
>     mail: mail
> ```

谢谢，该问题已修复。目前的问题是连接compute01的交互式应用（包括桌面和jupyer）无法启动，login01的桌面可以正常启动。报错如下：
![image](https://github.com/PKUHPC/SCOW/assets/79386690/4770d084-369b-4437-b817-e212a27c7ffb)
但login01桌面服务连接成功后显示如下
![image](https://github.com/PKUHPC/SCOW/assets/79386690/24a79bcf-ea29-4105-84e2-fd86f3a61911)

**Comment by huangjun0210** [comment]
看看你的家目录权限，家目录下scow文件夹的权限，这个看起来是共享存储有点问题

**Comment by ZYFno996** [comment]
> 看看你的家目录权限，家目录下scow文件夹的权限，这个看起来是共享存储有点问题

检查了家目录权限，确实有点问题。修改之后已经正常。非常感谢！

**Comment by Gao-Yajie** [comment]
> > ![image](https://user-images.githubusercontent.com/26295600/279556140-2fb90cf5-43c7-4a69-90b6-6fa8f8966792.png) 这个错误解决了没
> 
> 重新调整ldap配置之后这个问题没有了，shell和文件管理都已恢复正常。现在的问题是：
> 
> ### Error： /mis/init 页面添加初始管理员时依然报500，日志如下
> ![image](https://github.com/PKUHPC/SCOW/assets/79386690/c1e2d8d3-8c2f-48b4-8e4e-00fb08acb032)
> 
> ### auth.yml
> ![image](https://github.com/PKUHPC/SCOW/assets/79386690/015250ee-f3e4-4aa9-b99f-ad23ef6797eb)



> 您好，SCOW系统已经部署完成，能够正常启动、操作用户。但shell、桌面、交互式应用、文件管理几个功能均无法使用，系统横幅消息“无法以用户身份连接到登录节点。请确认您的家目录的权限为700、750或者755”。
> 
> ### Shell报错
> Process exited with code 1 and signal undefined.
> 
> ### 桌面报错
> 横幅提示服务器错误500，日志报错如图 ![image](https://github.com/PKUHPC/SCOW/assets/79386690/a3614b0f-14f3-4d38-8b09-311b3382752c)
> 
> ### 交互式应用
> 进入创建页面横幅提示服务器错误500，日志报错如图 ![image](https://github.com/PKUHPC/SCOW/assets/79386690/b7ba5df7-5a82-43ae-a872-257af98d29f2) 提交创建时横幅提示服务器错误500，日志报错如图 ![image](https://github.com/PKUHPC/SCOW/assets/79386690/a771d231-d525-4bf5-86ce-c4be495f60c8)
> 
> ### 文件管理
> ![image](https://github.com/PKUHPC/SCOW/assets/79386690/7fdab75b-c474-4c37-b0a7-5fb1e045490b)
> 
> config/apps/、portal..yml配置均按照文档内容填充。请问SCOW用户登录是否与login节点上的系统用户有关？在登录节点用户根目录下出现了“~用户ID”文件夹，权限为755但仍无法顺利使用上述功能。根据手册目前无法知晓哪处配置有误，以及各个子系统用户之间的关联。望解答。

请问原问题是否解决了呢，我在http://10.88.152.51:8082/scow/portal/api/file/getHome接口也同样遇到该错误
