### ISSUE TITLE
vscode作业如何打开ipynb格式的文件？

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#934]
通过应用vscode 打开ipynb文件，一直加载中。

下面issue说是与https有关？https://github.com/coder/code-server/issues/5178

![image](https://github.com/PKUHPC/SCOW/assets/67989011/a82dceea-996e-41ab-aabc-d45da0c1ec81)

**Comment by vanstriker** [comment]
是否可以在demo集群https://hpc.pku.edu.cn/demo/scow中复现？

**Comment by lingbozeng** [comment]
demo集群是正常的，感觉像是和https有关

**Comment by zhengkang2020** [comment]
测试集群正常打开，是否确认是https的问题？

**Comment by lingbozeng** [comment]
对的，就是web协议的问题，https是可以的

**Comment by zhengkang2020** [comment]
那如何配置https访问呢？是要配置代理网关吗？
我这里nginx转发已经配置了，但是点击登录会跳转回登陆界面。

**Comment by lingbozeng** [comment]
可以参考这个配一下试试：https://www.nginx.org.cn/article/detail/539

**Comment by lingbozeng** [comment]
配置应该有问题，监听443端口，把http注释掉

**Comment by zhengkang2020** [comment]
http注释后登录找不到页面
![image](https://github.com/PKUHPC/SCOW/assets/67989011/e3ca602d-2b77-4e56-b8e9-e0a367150805)

**Comment by lingbozeng** [comment]
那http还是得要，是不是要去掉location里的proxy_redirect https:// http://;

**Comment by zhengkang2020** [comment]
去掉location里的proxy_redirect https:// http://; 后还是一样，点击登录时会返回到登陆界面，说登陆不进去

**Comment by zhengkang2020** [comment]
@lingbozeng 有其他需要配置的吗？

**Comment by zhengkang2020** [comment]
重新建了一个issue https://github.com/PKUHPC/SCOW/issues/946#issue-1975822001

**Comment by zhengkang2020** [comment]
按https://github.com/PKUHPC/SCOW/issues/946#issue-1975822001 配置了https，但是通过vscode打开ipynb报错，这个是证书错误还是需要其他配置？

![image](https://github.com/PKUHPC/SCOW/assets/67989011/5ffd91f7-f4c5-41eb-a1f9-c00cf14c7a8f)

**Comment by lingbozeng** [comment]
这个应该是证书的问题了

**Comment by zhengkang2020** [comment]
使用自签名证书会出现以上报错，使用`DigiCert Inc`签名的正式证书解决以上问题！感谢 @lingbozeng
