### ISSUE TITLE
初始化镜像下载出现问题

### ISSUE THREAD

**Issue by yuguoshao** [PKUHPC/SCOW#938]
执行./cli compose up -d命令 有如下报错

[root@localhost scow]# ./cli compose pull
INFO: Loaded plugins: []
[+] Pulling 12/12
 ✔ gateway Skipped - Image is already being pulled by audit-server                                                                                         0.0s 
 ✔ portal-server Skipped - Image is already being pulled by audit-server                                                                                   0.0s 
 ✔ portal-web Skipped - Image is already being pulled by audit-server                                                                                      0.0s 
 ✔ auth Skipped - Image is already being pulled by audit-server                                                                                            0.0s 
 ✔ db Skipped - Image is already being pulled by audit-db                                                                                                  0.0s 
 ✔ mis-server Skipped - Image is already being pulled by audit-server                                                                                      0.0s 
 ✔ mis-web Skipped - Image is already being pulled by audit-server                                                                                         0.0s 
 ✘ redis Error                                                                                                                                             0.2s 
 ✘ novnc Error                                                                                                                                             0.2s 
 ✘ audit-server Error                                                                                                                                      0.2s 
 ✘ audit-db Error                                                                                                                                          0.2s 
 ✘ log Error                                                                                                                                               0.2s 
Error response from daemon: Get "https://mirrors.pku.edu.cn/v2/": read tcp 172.16.200.19:47380->162.105.120.100:443: read: connection reset by peer

**Comment by huangjun0210** [comment]
这是拉的哪个版本的镜像？没拉下来，试试直接docker pull 拉一下镜像

**Comment by yuguoshao** [comment]
版本是v1.0.0
[root@localhost scow]# ./cli --version
1.0.0

我尝试手动拉镜像，依然不行
docker pull mirrors.pku.edu.cn/pkuhpc-icode/scow:master
Error response from daemon: Get "https://mirrors.pku.edu.cn/v2/": read tcp 172.16.200.19:48174->162.105.120.100:443: read: connection reset by peer

**Comment by huangjun0210** [comment]
![image](https://github.com/PKUHPC/SCOW/assets/26295600/b54acd8e-be5f-47fd-8de9-693ae9e42271)
拉镜像没问题，应该是你的网络的问题，尝试在网络好点的机器上试试

**Comment by yuguoshao** [comment]
谢谢
