### ISSUE TITLE
管理系统创建账户报错

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#939]
管理系统创建账户，如果账户名有大写字母或中文，会导致报错
![image](https://github.com/PKUHPC/SCOW/assets/67989011/d2f47383-aeab-4097-852d-a3078e54934b)

![image](https://github.com/PKUHPC/SCOW/assets/67989011/26443deb-be22-4672-8c41-f0fc5b97ae73)

这个问题会修复或优化吗？

**Comment by huangjun0210** [comment]
这里的账户时对应slurm中的账户，肯定是不能有中文的，另外为了和slurm数据库保持一致，我们建议账户中不能有大写字母

**Comment by zhengkang2020** [comment]
好的，这个是已知问题，且暂时不会解决。
