### ISSUE TITLE
交互式应用创建时报错500 undefined

### ISSUE THREAD

**Issue by ZYFno996** [PKUHPC/SCOW#947]
系统已经正确配置，ssh免密登录、ldap用户登录均无问题。系统其他功能无问题。日志报错Permission denied。
![image](https://github.com/PKUHPC/SCOW/assets/79386690/de946b3d-c5d7-459c-aa43-c2c5619e7075)

**Comment by huangjun0210** [comment]
https://github.com/PKUHPC/SCOW/issues/930#issuecomment-1790315356  不是解决了吗？

**Comment by ZYFno996** [comment]
> [#930 (comment)](https://github.com/PKUHPC/SCOW/issues/930#issuecomment-1790315356) 不是解决了吗？
您好，#930 解决的是shell和登录节点桌面的问题，现在交互式应用仍有报错。已经验证过ssh/sftp无误，能够正常访问、传输文件

**Comment by huangjun0210** [comment]
家目录下有个`scow`文件夹权限有没有问题？把这个文件夹删了再试试

**Comment by ZYFno996** [comment]
scow文件夹owner和group均对应当前登录用户，权限为755。修改其权限为777无改善。删除后只有使用过文件管理功能后才会自动建立scow文件夹。

**Comment by huangjun0210** [comment]
删除了再让其自动创建，在提交作业、交互式应用等功能的时候，若没有这个文件夹也会自动创建。

**Comment by ZYFno996** [comment]
> 删除了再让其自动创建，在提交作业、交互式应用等功能的时候，若没有这个文件夹也会自动创建。

删除之后新建交互式应用，依然报服务器错误500，未新建scow文件夹。
![image](https://github.com/PKUHPC/SCOW/assets/79386690/8fd89d7e-87d3-4d43-8df2-c57058c944c2)

![image](https://github.com/PKUHPC/SCOW/assets/79386690/68ed723d-3f93-4bfd-af39-e634a5a2df32)

**Comment by huangjun0210** [comment]
提交任务呢？看看生成的scow文件夹及其子文件夹权限

**Comment by ZYFno996** [comment]
> 提交任务呢？看看生成的scow文件夹及其子文件夹权限
提交作业生成的家目录为755，但scow目录在[家目录]/root/scow，而不是[家目录]/scow。这个会有问题吗？
![image](https://github.com/PKUHPC/SCOW/assets/79386690/72afe304-125f-4b02-9a96-7c17fcd36288)

**Comment by huangjun0210** [comment]
那你这个配置是不对的，应该没有root

**Comment by ZYFno996** [comment]
> 那你这个配置是不对的，应该没有root

这个地方为什么会生成root？是哪个配置在控制呢。我完全是按照教程还有issue回复配置的

**Comment by ZYFno996** [comment]
> 那你这个配置是不对的，应该没有root
这个地方的路径可以手动修改，但是默认路径是带root的。请问是哪个配置控制这个地方？之前操作一直是按手册和issue回复执行的
![image](https://github.com/PKUHPC/SCOW/assets/79386690/01ba35ee-39a0-4974-bb77-8e8086cb9339)

**Comment by ZYFno996** [comment]
> 这个应该是这个用户dap中的家目录是这个，需要改ldap
ldap中配置的家目录如下，没有root。另外只有提交作业是默认有root目录，shell和文件管理功能自动生成的路径没有root

![image](https://github.com/PKUHPC/SCOW/assets/79386690/64733f5a-5660-42fb-8411-f64cb1f1fe87)

**Comment by huangjun0210** [comment]
那应该没问题，加个微信：18163650606，远程看看
