### ISSUE TITLE
门户及管理系统中作业信息展示能否优化？

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#952]
门户系统查询的作业账户和分区信息长度2行。能否自动调整长度？
![image](https://github.com/PKUHPC/SCOW/assets/67989011/6bfee787-79a9-4829-ad8b-09e57c2da008)

![image](https://github.com/PKUHPC/SCOW/assets/67989011/8f6e6522-8815-464b-b400-dbfaaea263e9)

**Comment by tongchong** [comment]
可以，我们再优化一下这里

**Comment by tongchong** [comment]
如果想立刻见到效果的话，可以更新fix(web): 优化web端table展示效果，调整列的宽度 #954  的镜像

**Comment by tongchong** [comment]
会，后续会合并到主分支

**Comment by zhengkang2020** [comment]
这个问题优化后合并到主分支有具体时间吗？

**Comment by tongchong** [comment]
本周内应可以
