### ISSUE TITLE
文件管理中如何同时下载多个文件或者下载整个目录？

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#980]
目前文件管理中，文件只能一个一个下载，如何同时下载多个文件？或者如何下载整个目录？
![image](https://github.com/PKUHPC/SCOW/assets/67989011/1061cb97-a4f7-4735-9590-e9cdf31bb947)

**Comment by liu-shaobo** [comment]
好像没有这个功能，我是在自己在任务里面打包的。

**Comment by zhengkang2020** [comment]
能增加这个功能吗？

**Comment by vanstriker** [comment]
近期版本暂无增加该功能的计划，可以进入shell压缩打包后再下载
