### ISSUE TITLE
在slurm侧新建分区后，使用scow原来的账户无法在新分区提交作业

### ISSUE THREAD

**Issue by g-zhangpp** [PKUHPC/SCOW#996]
测试步骤：
1.平台中有用户t01_user01。
2.平台中有账户a_t01_account01，其拥有者是t01_user01。
3.在slurm侧增加一个新的分区gpu1。
4.使用t01_user01在账户a_t01_account01、新分区gpu1上提交作业失败。
5.但是如果再创建一个a_t01_account02账户，使用t01_user01在账户a_t01_account02、新分区gpu1上提交作业，却可以成功。

![微信图片_20231123154037](https://github.com/PKUHPC/SCOW/assets/46897488/52270c43-16fe-442b-a424-9d0e15858cc2)

**Comment by lingbozeng** [comment]
这个现在目前需要手动关联新创建的分区才行

**Comment by g-zhangpp** [comment]
请问，手动关联的命令是什么，能指导一下不

**Comment by vanstriker** [comment]
请在新版本查看是否还有该问题
